### ISSUE TITLE
明日方舟计算器结果乱码

### ISSUE THREAD

**Issue by sakurai-kaede** [Tsuk1ko/CQ-picfinder-robot#10]
![QQ图片20190627170316](https://user-images.githubusercontent.com/49109169/60252822-852d5800-98fd-11e9-885c-fe7450e3e10f.png)
如图

**Comment by Tsuk1ko** [comment]
如果你是部署在 Linux 上的话，估计是字体问题，你可以尝试修改这行代码

https://github.com/Tsuk1ko/CQ-picfinder-robot/blob/7307e00c6803df82c42127e41442aaaf1bd44b61/modules/plugin/akhr.draw.js#L48

因为我写的时候写死了微软雅黑，你可以尝试直接去掉或者改成 Linux 上有的字体，也可以试试在 Linux 上安装微软雅黑字体

比较建议部署在 Windows 服务器上，我目前没有在 Linux 下做过测试（所以是测试中的功能

如果以上方法有成功解决的话希望能反馈一下，我也好根据情况做出改进 \_(:3」∠)\_

**Comment by sakurai-kaede** [comment]
安装微软雅黑字体后成功
![QQ图片20190627174512](https://user-images.githubusercontent.com/49109169/60256018-5914d580-9903-11e9-902c-6355158680fe.png)
