### ISSUE TITLE
sauceNAO每日配额用完后报错

### ISSUE THREAD

**Issue by Magic-Xin** [Tsuk1ko/CQ-picfinder-robot#11]
如果sauceNAO每日配额用完后，会提示“saucenao[0] 搜索次数已达单位时间上限，请稍候再试”，且并不会继续使用ascii2d搜索。希望可以改良一下

**Comment by Tsuk1ko** [comment]
@Magic-Xin 也就是说改成配额用完后用 ascii2d 搜索吗，可以

**Comment by Magic-Xin** [comment]
感谢大佬！
