### ISSUE TITLE
请问sauceNAO每日配额上限的问题怎么解决？

### ISSUE THREAD

**Issue by AOALI123** [Tsuk1ko/CQ-picfinder-robot#12]

**Comment by AOALI123** [comment]
大佬您的竹竹我是见过的，很多人在用，没有配额上限这个问题貌似= = 请问如何解决

**Comment by Tsuk1ko** [comment]
那是因为我偷鸡了，具体方法是 config 中的 saucenaoHost 设置项，但这个方法也要求你有一些可以拿来这么用的服务器

我就说这么多，因为偷鸡也不是什么光明正大的事，要是你不明白那就算了（issue 我先关了

**Comment by AOALI123** [comment]
懂是懂了= = 就是不知道json的格式该是什么= =

**Comment by Tsuk1ko** [comment]
那个地方就是个数组

**Comment by AOALI123** [comment]
"saucenao.com"需要删掉吗 = = 还是说我后续跟上IP就行，我寻思您老这里写了网址，我怕不是剩下的服务器得内网穿透然后也填网址= =

**Comment by Tsuk1ko** [comment]
不用删，数组里的所有地址会轮流用

**Comment by AOALI123** [comment]
吼 懂了

**Comment by AOALI123** [comment]
我想了想，我应该还是缺关键的一步，数组里面应该填IP，然后呢？我IP所属的服务器要怎么做？如何通过我的IP访问到sauceNAO呢？

**Comment by AOALI123** [comment]
Nginx？

**Comment by Tsuk1ko** [comment]
嗯，想用什么都可以
