### ISSUE TITLE
SFW 功能，过滤R18搜索结果

### ISSUE THREAD

**Issue by miyouzi** [Tsuk1ko/CQ-picfinder-robot#13]
在搜索某些非R18图时，会意外搜出 R18 本子，结果导致 R18 图连带着链接一起发出，这在 QQ 群中很致命，希望能有屏蔽 R18 搜索结果的功能，或者R18搜索结果仅私聊可见

**Comment by Tsuk1ko** [comment]
@miyouzi 没有办法，本身 saucenao 并没有对这个做区分
不建议在 SFW 群内使用

**Comment by miyouzi** [comment]
那……退一步吧，比如屏蔽 nhentai 的搜索结果。

**Comment by Tsuk1ko** [comment]
@miyouzi 可以考虑增加一个默认搜索库的设置，做到在不加参数时默认只搜索p站图这样

**Comment by miyouzi** [comment]
可以。谢谢大佬！
