### ISSUE TITLE
关于明日方舟使用方法计算器

### ISSUE THREAD

**Issue by samondlee** [Tsuk1ko/CQ-picfinder-robot#15]
你好我截图羡慕界面并添加参数没有反应，按理说config已经打开该功能了呀
![Screenshot_20190813-112558_QQ](https://user-images.githubusercontent.com/8521327/62913213-cf8b6b00-bdbd-11e9-9fbc-2541a7aae2a7.jpg)

**Comment by Tsuk1ko** [comment]
@samondlee 请当查看程序日志，看看有什么报错

**Comment by samondlee** [comment]
![20190813_113844](https://user-images.githubusercontent.com/8521327/62913855-5e00ec00-bdc0-11e9-80ba-70437b048d44.jpg)
@Tsuk1ko

**Comment by Tsuk1ko** [comment]
这个错误是在发送 arkr 命令的时候出现的吗

**Comment by samondlee** [comment]
> 这个错误是在发送 arkr 命令的时候出现的吗

对的因该是

因为之前没用这个功能的时候 一直没有这个错误

**Comment by Tsuk1ko** [comment]
有点奇怪，这个请求是去 Cloudflare 的，但我没印象我有调用什么 Cloudflare 的服务

如果你的服务器在国内而且用的 ocr 是 ocr.space 的话，可能会无法连接，建议根据 README 中的说明注册并配置百度的 ocr
