### ISSUE TITLE
请问一下，这种情况是我哪里的配置出错了呢

### ISSUE THREAD

**Issue by HellSakura** [Tsuk1ko/CQ-picfinder-robot#17]
![image](https://user-images.githubusercontent.com/43169031/63312803-2b617100-c335-11e9-807f-a25456824263.png)

**Comment by Tsuk1ko** [comment]
cq-http 插件没有正确配置或启用

**Comment by HellSakura** [comment]
> cq-http插件没有正确配置或启用

![批注 2019-08-20 120148](https://user-images.githubusercontent.com/43169031/63316750-982f3800-c342-11e9-843e-39abc6a9bb60.png)
红线为服务器内网IP

**Comment by Tsuk1ko** [comment]
@HellSakura 看一下cq http的日志吧，有没有正常监听端口什么的，新版插件和旧版插件的配置不太一样

如果没有问题，尝试关闭Windows防火墙或者创建端口规则放行6700，我是曾经遇到过防火墙拦截localhost的奇怪情况

**Comment by HellSakura** [comment]
@Tsuk1ko 
![image](https://user-images.githubusercontent.com/43169031/63317548-e3971580-c345-11e9-99dc-afe06a8cb3b0.png)
防火墙关闭了，端口也放行了，这边日志是正常启动，感觉是不是我插件的config出问题了？

**Comment by Tsuk1ko** [comment]
ws 监听的端口是 6700 的话就应该没问题

你应该没有在机器人`config.json`里填`access_token`吧，得和 cq-http 的保持一致

**Comment by HellSakura** [comment]
`access_token` 已经设置，两边保持一致了，依然链接失败

**Comment by HellSakura** [comment]
@Tsuk1ko 
![批注 2019-08-20 120148](https://user-images.githubusercontent.com/43169031/63319774-c5cdae80-c34d-11e9-977e-699bc9ea731a.png)
![批注 2019-08-20 132331](https://user-images.githubusercontent.com/43169031/63319776-c7977200-c34d-11e9-9687-86dfefb32e7f.png)
这是两边的配置

**Comment by Tsuk1ko** [comment]
……你 cq-http 的配置，host 和 ws_host 保持`[::]`就行了，这是监听全部目的ip的意思，并且机器人的host也应维持`127.0.0.1`

并且，带中括号的地址是ipv6格式，`[::]`是ipv6中的环回地址，和`127.0.0.1`是同一个概念，并且包含`127.0.0.1`，我怀疑你下面是在中括号中写了ipv4地址，这是错误的

如果指定了一个非`127.0.0.1`的ip，比如外网ip，则只会监听目的ip为该ip的连接，这意味着你要在机器人配置里也指定连接该ip，而不能用`127.0.0.1`

**Comment by HellSakura** [comment]
> ……你 cq-http 的配置，host 和 ws_host 保持`[::]`就行了，这是监听全部目的ip的意思，并且机器人的host也应维持`127.0.0.1`
> 
> 并且，带中括号的地址是ipv6格式，`[::]`是ipv6中的环回地址，和`127.0.0.1`是同一个概念，并且包含`127.0.0.1`，我怀疑你下面是在中括号中写了ipv4地址，这是错误的
> 
> 如果指定了一个非`127.0.0.1`的ip，比如外网ip，则只会监听目的ip为该ip的连接，这意味着你要在机器人配置里也指定连接该ip，而不能用`127.0.0.1`

是的，问题已经解决，正常运行，感谢
