### ISSUE TITLE
你好,我的系统是mac,用的酷Q docker， 运行成功，发送图片，总是提示搜索失败，请问怎么解决?

### ISSUE THREAD

**Issue by YumikoAzu** [Tsuk1ko/CQ-picfinder-robot#19]
<img width="433" alt="test" src="https://user-images.githubusercontent.com/13196251/63480256-c12b0680-c4c3-11e9-91dd-b91869c6a749.png">
<img width="358" alt="tests" src="https://user-images.githubusercontent.com/13196251/63480370-40b8d580-c4c4-11e9-8e95-77dbc875a0be.png">

**Comment by Tsuk1ko** [comment]
有可能是网络不畅，你这里打得开 http://saucenao.com/ 么

如果打得开没问题，`git pull`更新一下并重启程序，我增加了详细的错误输出

**Comment by YumikoAzu** [comment]
> 有可能是网络不畅，你这里打得开 http://saucenao.com/ 么
> 
> 如果打得开没问题，`git pull`更新一下并重启程序，我增加了详细的错误输出

我刚刚把ssr的PAC加了这个网站,可以打开。
<img width="632" alt="t1" src="https://user-images.githubusercontent.com/13196251/63482777-baed5800-c4cc-11e9-8cba-5ee131e83fe6.png">

报错日志如下：
0|cqpf  | 2019-8-22 11:03:10 AM [error] saucenao[0][request]
0|cqpf  | { Error: read ECONNRESET
0|cqpf  |     at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
0|cqpf  |   errno: 'ECONNRESET',
0|cqpf  |   code: 'ECONNRESET',
0|cqpf  |   syscall: 'read',
0|cqpf  |   config:
0|cqpf  |    { url: 'http://saucenao.com/search.php',
0|cqpf  |      method: 'get',
0|cqpf  |      params:
0|cqpf  |       { db: 999,
0|cqpf  |         output_type: 2,
0|cqpf  |         numres: 3,
0|cqpf  |         url:
0|cqpf  |          'https://c2cpicdw.qpic.cn/offpic_new/304785950//e3c78fb2-1a28-4215-a143-e7fe2beeda5a/0?vuin=3481659824&amp;term=2' },
0|cqpf  |      headers:
0|cqpf  |       { Accept: 'application/json, text/plain, */*',
0|cqpf  |         'User-Agent': 'axios/0.19.0' },
0|cqpf  |      transformRequest: [ [Function: transformRequest] ],
0|cqpf  |      transformResponse: [ [Function: transformResponse] ],
0|cqpf  |      timeout: 0,
0|cqpf  |      adapter: [Function: httpAdapter],
0|cqpf  |      xsrfCookieName: 'XSRF-TOKEN',
0|cqpf  |      xsrfHeaderName: 'X-XSRF-TOKEN',
0|cqpf  |      maxContentLength: -1,
0|cqpf  |      validateStatus: [Function: validateStatus],
0|cqpf  |      data: undefined },
0|cqpf  |   request:
0|cqpf  |    Writable {
0|cqpf  |      _writableState:
0|cqpf  |       WritableState {
0|cqpf  |         objectMode: false,
0|cqpf  |         highWaterMark: 16384,
0|cqpf  |         finalCalled: false,
0|cqpf  |         needDrain: false,
0|cqpf  |         ending: false,
0|cqpf  |         ended: false,
0|cqpf  |         finished: false,
0|cqpf  |         destroyed: false,
0|cqpf  |         decodeStrings: true,
0|cqpf  |         defaultEncoding: 'utf8',
0|cqpf  |         length: 0,
0|cqpf  |         writing: false,
0|cqpf  |         corked: 0,
0|cqpf  |         sync: true,
0|cqpf  |         bufferProcessing: false,
0|cqpf  |         onwrite: [Function: bound onwrite],
0|cqpf  |         writecb: null,
0|cqpf  |         writelen: 0,
0|cqpf  |         bufferedRequest: null,
0|cqpf  |         lastBufferedRequest: null,
0|cqpf  |         pendingcb: 0,
0|cqpf  |         prefinished: false,
0|cqpf  |         errorEmitted: false,
0|cqpf  |         emitClose: true,
0|cqpf  |         autoDestroy: false,
0|cqpf  |         bufferedRequestCount: 0,
0|cqpf  |         corkedRequestsFree: [Object] },
0|cqpf  |      writable: true,
0|cqpf  |      domain: null,
0|cqpf  |      _events:
0|cqpf  |       [Object: null prototype] {
0|cqpf  |         response: [Function: handleResponse],
0|cqpf  |         error: [Function: handleRequestError] },
0|cqpf  |      _eventsCount: 2,
0|cqpf  |      _maxListeners: undefined,
0|cqpf  |      _options:
0|cqpf  |       { protocol: 'http:',
0|cqpf  |         maxRedirects: 21,
0|cqpf  |         maxBodyLength: 10485760,
0|cqpf  |         path:
0|cqpf  |          '/search.php?db=999&output_type=2&numres=3&url=https:%2F%2Fc2cpicdw.qpic.cn%2Foffpic_new%2F304785950%2F%2Fe3c78fb2-1a28-4215-a143-e7fe2beeda5a%2F0%3Fvuin%3D3481659824%26amp%3Bterm%3D2',
0|cqpf  |         method: 'GET',
0|cqpf  |         headers: [Object],
0|cqpf  |         agent: undefined,
0|cqpf  |         auth: undefined,
0|cqpf  |         hostname: 'saucenao.com',
0|cqpf  |         port: null,
0|cqpf  |         nativeProtocols: [Object],
0|cqpf  |         pathname: '/search.php',
0|cqpf  |         search:
0|cqpf  |          '?db=999&output_type=2&numres=3&url=https:%2F%2Fc2cpicdw.qpic.cn%2Foffpic_new%2F304785950%2F%2Fe3c78fb2-1a28-4215-a143-e7fe2beeda5a%2F0%3Fvuin%3D3481659824%26amp%3Bterm%3D2' },
0|cqpf  |      _redirectCount: 0,
0|cqpf  |      _redirects: [],
0|cqpf  |      _requestBodyLength: 0,
0|cqpf  |      _requestBodyBuffers: [],
0|cqpf  |      _onNativeResponse: [Function],
0|cqpf  |      _currentRequest:
0|cqpf  |       ClientRequest {
0|cqpf  |         domain: null,
0|cqpf  |         _events: [Object],
0|cqpf  |         _eventsCount: 6,
0|cqpf  |         _maxListeners: undefined,
0|cqpf  |         output: [],
0|cqpf  |         outputEncodings: [],
0|cqpf  |         outputCallbacks: [],
0|cqpf  |         outputSize: 0,
0|cqpf  |         writable: true,
0|cqpf  |         _last: true,
0|cqpf  |         chunkedEncoding: false,
0|cqpf  |         shouldKeepAlive: false,
0|cqpf  |         useChunkedEncodingByDefault: false,
0|cqpf  |         sendDate: false,
0|cqpf  |         _removedConnection: false,
0|cqpf  |         _removedContLen: false,
0|cqpf  |         _removedTE: false,
0|cqpf  |         _contentLength: 0,
0|cqpf  |         _hasBody: true,
0|cqpf  |         _trailer: '',
0|cqpf  |         finished: true,
0|cqpf  |         _headerSent: true,
0|cqpf  |         socket: [Socket],
0|cqpf  |         connection: [Socket],
0|cqpf  |         _header:
0|cqpf  |          'GET /search.php?db=999&output_type=2&numres=3&url=https:%2F%2Fc2cpicdw.qpic.cn%2Foffpic_new%2F304785950%2F%2Fe3c78fb2-1a28-4215-a143-e7fe2beeda5a%2F0%3Fvuin%3D3481659824%26amp%3Bterm%3D2 HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.19.0\r\nHost: saucenao.com\r\nConnection: close\r\n\r\n',
0|cqpf  |         _onPendingData: [Function: noopPendingOutput],
0|cqpf  |         agent: [Agent],
0|cqpf  |         socketPath: undefined,
0|cqpf  |         timeout: undefined,
0|cqpf  |         method: 'GET',
0|cqpf  |         path:
0|cqpf  |          '/search.php?db=999&output_type=2&numres=3&url=https:%2F%2Fc2cpicdw.qpic.cn%2Foffpic_new%2F304785950%2F%2Fe3c78fb2-1a28-4215-a143-e7fe2beeda5a%2F0%3Fvuin%3D3481659824%26amp%3Bterm%3D2',
0|cqpf  |         _ended: false,
0|cqpf  |         res: null,
0|cqpf  |         aborted: undefined,
0|cqpf  |         timeoutCb: null,
0|cqpf  |         upgradeOrConnect: false,
0|cqpf  |         parser: null,
0|cqpf  |         maxHeadersCount: null,
0|cqpf  |         _redirectable: [Circular],
0|cqpf  |         [Symbol(isCorked)]: false,
0|cqpf  |         [Symbol(outHeadersKey)]: [Object] },
0|cqpf  |      _currentUrl:
0|cqpf  |       'http://saucenao.com/search.php?db=999&output_type=2&numres=3&url=https:%2F%2Fc2cpicdw.qpic.cn%2Foffpic_new%2F304785950%2F%2Fe3c78fb2-1a28-4215-a143-e7fe2beeda5a%2F0%3Fvuin%3D3481659824%26amp%3Bterm%3D2' },
0|cqpf  |   response: undefined,
0|cqpf  |   isAxiosError: true,
0|cqpf  |   toJSON: [Function] }

**Comment by Tsuk1ko** [comment]
看起来是网络问题，你目前的网络无法直连 saucenao，会被连接重置

ssr 是无法直接代理 node 程序发出的请求的，我目前也没有专门做代理配置，因为需求情景很少（下个版本加个设置吧）

正式使用建议还是将机器人部署在服务器上，最好是国外的

**Comment by YumikoAzu** [comment]
> 看起来是网络问题，你目前的网络无法直连 saucenao，会被连接重置
> 
> ssr 是无法直接代理 node 程序发出的请求的，我目前也没有专门做代理配置，因为需求情景很少（下个版本加个设置吧）
> 
> 正式使用建议还是将机器人部署在服务器上，最好是国外的

噢噢，好吧~感谢回答~
