### ISSUE TITLE
你好，搜图搜到本子的时候只会返回相似度和原图

### ISSUE THREAD

**Issue by yuukia0** [Tsuk1ko/CQ-picfinder-robot#20]
![2222](https://user-images.githubusercontent.com/38274638/63522098-4ba65100-c52a-11e9-8a6a-187fe840b94a.png)
如图，搜索本子封面不能正常返回结果
下面开debug模式看了一下返回的问题（可惜并不是很懂
![11111](https://user-images.githubusercontent.com/38274638/63522100-4ba65100-c52a-11e9-9a65-28e6f8ac6019.png)
用的windows server 2012 R2，谢谢~

**Comment by Tsuk1ko** [comment]
怀疑是服务器所在网络无法访问 nhentai，受到连接重置之类的干扰

**Comment by Tsuk1ko** [comment]
新版已经支持配置 http 或者 socks 代理，如果有网络问题请尝试利用小飞机

**Comment by yuukia0** [comment]
配置代理解决了，感谢:)
