### ISSUE TITLE
新图像服务添加请求

### ISSUE THREAD

**Issue by jokkkkk** [Tsuk1ko/CQ-picfinder-robot#23]
**功能描述**
很高的无水印下的识别率且提供多服务源支持

**理由**
可以搜到大部分无法搜到的局部图且支持gif

**附加信息**
网址是 https://tineye.com/
如果大大还有精力的话还可以配合 https://web.archive.org/ 来实现快照抓取解决404

**Comment by Tsuk1ko** [comment]
@jokkkkk 好的，周末看看

虽然 tineye 很久以前就知道，但我从来没想过用它搜插画😂

**Comment by Tsuk1ko** [comment]
测试了下手头随便找了几张插画，发现 tineye 什么也没搜出来 🤔

你有能被搜出来的例子么，以及看这个表现我觉得它不适合用来搜插画

**Comment by jokkkkk** [comment]
https://send.firefox.com/download/91bf90117cfedaa8/#1fXNFxIJNw4X8oiPv0vnGw
找了三张比较有代表性的，tineye建议只带常规搜索后无法匹配或者是局部图时辅助使用
大部分局部图使用tineye找到低分辨率完整图时就可以用常规搜索找到高分辨率

**Comment by Tsuk1ko** [comment]
OK，不幸的是，看了下 Tineye 搜图时候的请求，用了 Google 的 reCAPTCHA 做人机验证……

Tineye 本身有提供 API 服务，但是是付费的而且价格不菲
<https://services.tineye.com/TinEyeAPI#plans-and-pricing>

所以很抱歉，这个功能没办法做了😂

**Comment by jokkkkk** [comment]
了解了那这个issue我就关闭了
