### ISSUE TITLE
pm2 start后无反应，log中有报错

### ISSUE THREAD

**Issue by Magic-Xin** [Tsuk1ko/CQ-picfinder-robot#25]
> 1|CQPF  | 10/21/2019, 2:27:02 PM 连接中[/api]#12
1|CQPF  | 10/21/2019, 2:27:02 PM 连接错误[/api]
1|CQPF  | { SocketError: Failed to establish the websocket connection.
1|CQPF  |     at W3CWebSocket._sock.addEventListener (/root/CQ-picfinder-robot/node_modules/_cq-websocket@1.8.1@cq-websocket/src/index.js:451:70)
1|CQPF  |     at W3CWebSocket._dispatchEvent [as dispatchEvent] (/root/CQ-picfinder-robot/node_modules/_yaeti@0.0.6@yaeti/lib/EventTarget.js:115:12)
1|CQPF  |     at W3CWebSocket.onConnectFailed (/root/CQ-picfinder-robot/node_modules/_websocket@1.0.30@websocket/lib/W3CWebSocket.js:217:14)
1|CQPF  |     at WebSocketClient.<anonymous> (/root/CQ-picfinder-robot/node_modules/_websocket@1.0.30@websocket/lib/W3CWebSocket.js:59:25)
1|CQPF  |     at WebSocketClient.emit (events.js:198:13)
1|CQPF  |     at WebSocketClient.EventEmitter.emit (domain.js:448:20)
1|CQPF  |     at ClientRequest.handleRequestError (/root/CQ-picfinder-robot/node_modules/_websocket@1.0.30@websocket/lib/WebSocketClient.js:227:14)
1|CQPF  |     at ClientRequest.emit (events.js:198:13)
1|CQPF  |     at ClientRequest.EventEmitter.emit (domain.js:448:20)
1|CQPF  |     at Socket.socketOnEnd (_http_client.js:426:9) name: 'SocketError' }
1|CQPF  | 10/21/2019, 2:27:02 PM 连接失败[/api]#12

阿里云ECS
Ubuntu 18.04 bionic

昨天晚上在2.9.1就这样了，今天git pull了2.9.2，报错依旧。
已尝试删除并重新部署docker和机器人

**Comment by Tsuk1ko** [comment]
docker 是否有映射 cqhttp websocket 通信用的 6700 端口？

你可以参考 https://cqhttp.cc/docs/4.12/#/?id=%E4%BD%BF%E7%94%A8-docker

**Comment by Magic-Xin** [comment]
> 6700/tcp -> 0.0.0.0:6700
> 9000/tcp -> 0.0.0.0:9000

6700和9000端口都有映射的

**Comment by Tsuk1ko** [comment]
既然确认没有问题那我也不清楚了

除此之外只能建议你检查cqhttp插件启用情况以及cqhttp配置是否正确配置，特别是 use_ws 有没有开启

可以的话贴一下cqhttp配置文件我检查下

我没用过docker版也无法想象出其他可能的原因

**Comment by Magic-Xin** [comment]
我把cqhttp的配置文件删了，重启docker让它重新生成了一个，再改了一遍use_ws: true，就好了
可能之前那份是我FTP下来改完上传的，这次直接在vim里改的就正常了

感谢大佬提供的帮助！
