### ISSUE TITLE
Docker版酷Q无法正常发送图片

### ISSUE THREAD

**Issue by bymoye** [Tsuk1ko/CQ-picfinder-robot#26]
显示：文件名不合法，无法发送！(https://i.pximg.net/img-original/img/2019/08/24/13/50/18/76432110_p0.png)
配置文件为：		
"setu": {
			"enable": true,
			"allowPM": true,
			"pximgServerPort": "60233",
			"usePximgAddr": "",
			"pximgProxy": "https://i.pximg.net/",
			"deleteTime": 0,
			"cd": 30,
			"limit": 30,
			"whiteGroup": [],
			"whiteOnly": false,
			"whiteCd": 0,
			"whiteDeleteTime": 0,
			"r18OnlyInWhite": true
		},

**Comment by Tsuk1ko** [comment]
如果你不懂 pximgProxy 是做什么的请留空

**Comment by Tsuk1ko** [comment]
以及配置 docker 的端口映射

**Comment by bymoye** [comment]
orz端口映射做了的...因为之前版本也是这么配置的 但是更新版本之后就不行了

**Comment by Tsuk1ko** [comment]
🤔 pximgProxy 留空，usePximgAddr 配置为`<母鸡IP>:<60233映射到的端口>`
