### ISSUE TITLE
版本更新后的一系列错误

### ISSUE THREAD

**Issue by DazaiYuki** [Tsuk1ko/CQ-picfinder-robot#27]
**描述这个 bug**
之前大概是2.6的版本稳定使用几个月直到更新这次setu的规则
在使用node8以外的版本无论如何都不能正常使用
在使用node8时不认新的规则（指色图）

**如何复现**
复现步骤（如果能复现）
1. 打开酷Q
2. HTTP运行正常
3. npm start或 npm pm2 start
4. 出现 bug

**期望现象**
能开就好qwq 最好能用上新功能
**截图及日志**
- 问题相关截图
使用以下配置且在node8.16的情况下能正常开启，使用10和12就会有sqlite字眼的报错
![image](https://user-images.githubusercontent.com/54615306/67503878-5e243e80-f6c3-11e9-89b4-ac801d254e87.png)
然后使用node8.16的情况下用以下配置会报错且提示就是这一段文字的锅
![image](https://user-images.githubusercontent.com/54615306/67504300-181baa80-f6c4-11e9-9229-4979fa787f61.png)
手动把$^?删掉就能制止报错（咱也不知道为什么）
使用8以外的版本就会有以下Npmlog标的错误 而且使用pm2时会疯狂闪窗口 nodejs占满CPU
![20191025011233](https://user-images.githubusercontent.com/54615306/67504560-8fe9d500-f6c4-11e9-9c4f-ee036f421f09.png)

- 日志内容（复制粘贴或截图，复制粘贴请包裹在代码块中）
node8以外的版本输入npm start时的报错
C:\Users\Administrator\Documents\CQ-picfinder-robot\node_modules\sqlite3\lib\sqlite3.js:1
Error: Cannot find module 'C:\\Users\\Administrator\\Documents\\CQ-picfinder-robot\\node_modules\\sqlite3\\lib\\binding\\node-v64-win32-x64\\node_sqlite3.node'
    at Object.<anonymous> (C:\Users\Administrator\Documents\CQ-picfinder-robot\node_modules\sqlite3\lib\sqlite3.js:4:15)
C:\Users\Administrator\Documents\CQ-picfinder-robot\node_modules\sqlite3\lib\sqlite3.js:1
Error: Cannot find module 'C:\\Users\\Administrator\\Documents\\CQ-picfinder-robot\\node_modules\\sqlite3\\lib\\binding\\node-v64-win32-x64\\node_sqlite3.node'

npm的log
[2019-10-24T15_42_37_652Z-debug.log](https://github.com/Tsuk1ko/CQ-picfinder-robot/files/3768490/2019-10-24T15_42_37_652Z-debug.log)
[2019-10-24T15_43_40_763Z-debug.log](https://github.com/Tsuk1ko/CQ-picfinder-robot/files/3768491/2019-10-24T15_43_40_763Z-debug.log)
[2019-10-24T15_39_39_074Z-debug.log](https://github.com/Tsuk1ko/CQ-picfinder-robot/files/3768492/2019-10-24T15_39_39_074Z-debug.log)

**平台**
 - 操作系统：Win Server 2012 R2
 - Node 版本：8.16.2 / 10.16.3 / 12.12.0 (后两者无论如何操作都不能启动)

**附加内容**
重装node和换npm版本等操作都试过，之后考虑更换Linux环境

**Comment by Tsuk1ko** [comment]
sqlite 的问题应该是`npm i`的时候没有找到符合系统的预编译二进制文件，但在通常情况下会 fallback 进行编译，有可能是因为缺少 python 或 VC 运行库导致编译失败，可以的话请重新 clone 一份项目`npm i `并关注输出内容

至于正则表达式的问题，貌似确实在某些 node 版本下会有报错，有人反馈删除 ^ $ 即可正常，目前看来这不是个例，我会修改一下默认配置

我使用的是 10.16.0 版本一切正常，如果实在无法解决也可以尝试切换到该版本，以及我没记错的话 node 安装程序在安装结束时会询问或有选项勾选是否安装辅助工具（大概是这个意思），应该可以解决我一开始说的问题

**Comment by Tsuk1ko** [comment]
啊，另外提一点，pm2 是守护工具，所以当程序本身有错误退出之后会一直重复重启，造成你说的 cpu 占满的情况，`npm run pm2stop`即可停止

所以我在 wiki 中也有写到，首次运行建议直接 `npm start`，确定没有错误的时候再使用 pm2 守护

**Comment by Tsuk1ko** [comment]
emmm，手动`npm i sqlite`看下？

正则表达式的问题我明天改用 named-js-regexp 看看吧

**Comment by DazaiYuki** [comment]
![image](https://user-images.githubusercontent.com/54615306/67511460-ead5f900-f6d1-11e9-986c-74a5481f05f5.png)
![image](https://user-images.githubusercontent.com/54615306/67511491-f75a5180-f6d1-11e9-89c8-e1cfd8ce9467.png)
换到了10.16.3一顿操作后的结果(绝望)
npm audit fix的话一次报错后暂时在缓慢进行
![image](https://user-images.githubusercontent.com/54615306/67511855-ad25a000-f6d2-11e9-8300-bf40c12e2eb7.png)
（先挣扎一会）

**Comment by DazaiYuki** [comment]
![image](https://user-images.githubusercontent.com/54615306/67512820-997b3900-f6d4-11e9-8472-a17ea64fa0e1.png)
大概几分钟过去了 我觉得可以晾到明天再说

**Comment by Tsuk1ko** [comment]
@DazaiYuki 这个就是 fallback 到编译了

**Comment by DazaiYuki** [comment]
看这样子像是缺了py导致的，先搞个试试orz

**Comment by DazaiYuki** [comment]
![image](https://user-images.githubusercontent.com/54615306/67537833-a8331180-f70f-11e9-8380-e1a5d1bbbd6b.png)
一顿操作后变成了这样
装Node的过程一直都是狂点下一步 理论上也没漏啥
![image](https://user-images.githubusercontent.com/54615306/67537962-1d9ee200-f710-11e9-8d02-d09d3b7c6252.png)
现在装回8也会这样了（悲）
![image](https://user-images.githubusercontent.com/54615306/67538062-7e2e1f00-f710-11e9-870f-b51b2ae4fb49.png)

**Comment by Tsuk1ko** [comment]
换 Node 版本时如果 node module version 变了要删掉 node_modules 重新`npm i`，或者重新 clone

https://nodejs.org/zh-cn/download/releases/

你可以在这里看到各个版本的 node module version

像 canvas 和 sqlite3 这种需要预编译二进制可执行文件的，都是根据 node module version 和系统预编译的，变了的话以前的就不能使用了

**Comment by Tsuk1ko** [comment]
尝试使用这个分支，看看有没有解决正则表达式错误的问题

https://github.com/Tsuk1ko/CQ-picfinder-robot/tree/named-js-regexp

**Comment by Tsuk1ko** [comment]
@DazaiYuki 我用的 Windows Server 2019
命令行用 MingGW，装 git 的时候带的那个

**Comment by DazaiYuki** [comment]
![image](https://user-images.githubusercontent.com/54615306/67570466-0be72a00-f764-11e9-95bd-a8414f00fd35.png)
试了下那个分支 大概还是这样
这次重置到2012以后装好node8.16和git之后直接`git clone https://github.com/Tsuk1ko/CQ-picfinder-robot.git`然后`npm i`出现两个WARN以后忽略
用了新的配置还是会炸 然后旧的没事 
![%VP%DWIIZ8(IF}OMCE `UGM](https://user-images.githubusercontent.com/54615306/67570645-831cbe00-f764-11e9-8adf-9065432028ed.jpg)

**Comment by Catkamakura** [comment]
问一下这种情况是哪里出现的问题？
```
`2019-10-26 08:10:01 连接失败[/event]#2
2019-10-26 08:10:01 连接错误[/api]
{ SocketError: Failed to establish the websocket connection.
    at W3CWebSocket._sock.addEventListener (/root/CQ-picfinder-robot/node_modules/cq-websocket/src/index.js:451:70)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/root/CQ-picfinder-robot/node_modules/yaeti/lib/EventTarget.js:115:12)
    at W3CWebSocket.onConnectFailed (/root/CQ-picfinder-robot/node_modules/websocket/lib/W3CWebSocket.js:217:14)
    at WebSocketClient.<anonymous> (/root/CQ-picfinder-robot/node_modules/websocket/lib/W3CWebSocket.js:59:25)
    at emitOne (events.js:116:13)
    at WebSocketClient.emit (events.js:211:7)
    at ClientRequest.handleRequestError (/root/CQ-picfinder-robot/node_modules/websocket/lib/WebSocketClient.js:227:14)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:401:9) name: 'SocketError' }
2019-10-26 08:10:01 连接失败[/api]#2`
```

**Comment by DazaiYuki** [comment]
> 问一下这种情况是哪里出现的问题？
> 
> ```
> `2019-10-26 08:10:01 连接失败[/event]#2
> 2019-10-26 08:10:01 连接错误[/api]
> { SocketError: Failed to establish the websocket connection.
>     at W3CWebSocket._sock.addEventListener (/root/CQ-picfinder-robot/node_modules/cq-websocket/src/index.js:451:70)
>     at W3CWebSocket._dispatchEvent [as dispatchEvent] (/root/CQ-picfinder-robot/node_modules/yaeti/lib/EventTarget.js:115:12)
>     at W3CWebSocket.onConnectFailed (/root/CQ-picfinder-robot/node_modules/websocket/lib/W3CWebSocket.js:217:14)
>     at WebSocketClient.<anonymous> (/root/CQ-picfinder-robot/node_modules/websocket/lib/W3CWebSocket.js:59:25)
>     at emitOne (events.js:116:13)
>     at WebSocketClient.emit (events.js:211:7)
>     at ClientRequest.handleRequestError (/root/CQ-picfinder-robot/node_modules/websocket/lib/WebSocketClient.js:227:14)
>     at emitOne (events.js:116:13)
>     at ClientRequest.emit (events.js:211:7)
>     at Socket.socketErrorListener (_http_client.js:401:9) name: 'SocketError' }
> 2019-10-26 08:10:01 连接失败[/api]#2`
> ```


![QQ图片20191027011449](https://user-images.githubusercontent.com/54615306/67623393-467dbf00-f857-11e9-9d89-8f7468c9009e.png)
HTTP API的窗口消失 酷Q报错的时候 就会循环这段
消失原因不明，现在在确认是不是因为装了个地震监控的锅（但这个插件用不到HTTP API）
HTTP本身除了搜图机器人就只是多带了个塔塔露

**Comment by Catkamakura** [comment]
> > 问一下这种情况是哪里出现的问题？
> > ```
> > `2019-10-26 08:10:01 连接失败[/event]#2
> > 2019-10-26 08:10:01 连接错误[/api]
> > { SocketError: Failed to establish the websocket connection.
> >     at W3CWebSocket._sock.addEventListener (/root/CQ-picfinder-robot/node_modules/cq-websocket/src/index.js:451:70)
> >     at W3CWebSocket._dispatchEvent [as dispatchEvent] (/root/CQ-picfinder-robot/node_modules/yaeti/lib/EventTarget.js:115:12)
> >     at W3CWebSocket.onConnectFailed (/root/CQ-picfinder-robot/node_modules/websocket/lib/W3CWebSocket.js:217:14)
> >     at WebSocketClient.<anonymous> (/root/CQ-picfinder-robot/node_modules/websocket/lib/W3CWebSocket.js:59:25)
> >     at emitOne (events.js:116:13)
> >     at WebSocketClient.emit (events.js:211:7)
> >     at ClientRequest.handleRequestError (/root/CQ-picfinder-robot/node_modules/websocket/lib/WebSocketClient.js:227:14)
> >     at emitOne (events.js:116:13)
> >     at ClientRequest.emit (events.js:211:7)
> >     at Socket.socketErrorListener (_http_client.js:401:9) name: 'SocketError' }
> > 2019-10-26 08:10:01 连接失败[/api]#2`
> > ```
> 
> ![QQ图片20191027011449](https://user-images.githubusercontent.com/54615306/67623393-467dbf00-f857-11e9-9d89-8f7468c9009e.png)
> HTTP API的窗口消失 酷Q报错的时候 就会循环这段
> 消失原因不明，现在在确认是不是因为装了个地震监控的锅（但这个插件用不到HTTP API）
> HTTP本身除了搜图机器人就只是多带了个塔塔露

能看下你的httpapi配置文件和机器人配置文件吗，我是在aws centOS7 上布置的，使用http api的就只有这个机器人。
node v8.16.2下
`npm start`
后就是这个问题，因为是第一次布置机器人，我现在怀疑是我配置文件的问题

**Comment by DazaiYuki** [comment]
> > > 问一下这种情况是哪里出现的问题？
> > > ```
> > > `2019-10-26 08:10:01 连接失败[/event]#2
> > > 2019-10-26 08:10:01 连接错误[/api]
> > > { SocketError: Failed to establish the websocket connection.
> > >     at W3CWebSocket._sock.addEventListener (/root/CQ-picfinder-robot/node_modules/cq-websocket/src/index.js:451:70)
> > >     at W3CWebSocket._dispatchEvent [as dispatchEvent] (/root/CQ-picfinder-robot/node_modules/yaeti/lib/EventTarget.js:115:12)
> > >     at W3CWebSocket.onConnectFailed (/root/CQ-picfinder-robot/node_modules/websocket/lib/W3CWebSocket.js:217:14)
> > >     at WebSocketClient.<anonymous> (/root/CQ-picfinder-robot/node_modules/websocket/lib/W3CWebSocket.js:59:25)
> > >     at emitOne (events.js:116:13)
> > >     at WebSocketClient.emit (events.js:211:7)
> > >     at ClientRequest.handleRequestError (/root/CQ-picfinder-robot/node_modules/websocket/lib/WebSocketClient.js:227:14)
> > >     at emitOne (events.js:116:13)
> > >     at ClientRequest.emit (events.js:211:7)
> > >     at Socket.socketErrorListener (_http_client.js:401:9) name: 'SocketError' }
> > > 2019-10-26 08:10:01 连接失败[/api]#2`
> > > ```
> > 
> > 
> > ![QQ图片20191027011449](https://user-images.githubusercontent.com/54615306/67623393-467dbf00-f857-11e9-9d89-8f7468c9009e.png)
> > HTTP API的窗口消失 酷Q报错的时候 就会循环这段
> > 消失原因不明，现在在确认是不是因为装了个地震监控的锅（但这个插件用不到HTTP API）
> > HTTP本身除了搜图机器人就只是多带了个塔塔露
> 
> 能看下你的httpapi配置文件和机器人配置文件吗，我是在aws centOS7 上布置的，使用http api的就只有这个机器人。
> node v8.16.2下
> `npm start`
> 后就是这个问题，因为是第一次布置机器人，我现在怀疑是我配置文件的问题

我看了一下 就只是按要求把use_ws改为了true 其他默认

![image](https://user-images.githubusercontent.com/54615306/67623596-b55c1780-f859-11e9-8fe6-3dd9b8cbee32.png)

**Comment by Tsuk1ko** [comment]
@Catkamakura 若使用 docker 版酷Q，你还需要映射 6700 端口

**Comment by Tsuk1ko** [comment]
> 试了下那个分支 大概还是这样
> 这次重置到2012以后装好node8.16和git之后直接`git clone https://github.com/Tsuk1ko/CQ-picfinder-robot.git`然后`npm i`出现两个WARN以后忽略
> 用了新的配置还是会炸 然后旧的没事
> 
> 不过前三条规则带^和$都没出错，我猜大概是因为第四条的问号导致的吧
> 
> 然后补充一下 用setu功能的时候遇到某个图片半天不出来的情况会导致机器人不响应之后的所有指令，直到这张图出来为止 后台也没有弹错误信息

来尝试新的分支 https://github.com/Tsuk1ko/CQ-picfinder-robot/tree/named-regexp-groups

至于第二点问题估计是原图太大网速慢所以下载要卡很久，由于这个操作是 HTTP API 插件处理的所以我没有办法，但新版本加了个选项可以发送 master1200 图来减小网络消耗（帮忙测一下上面的分支，OK 就更

**Comment by DazaiYuki** [comment]
挂了一个下午回来发现canvas还是没装上
🤔前面确实没切到分支 我以为在对应的分支页点了clone就已经是了
然后其实我输了`git branch remotes/origin/named-regexp-groups`没反应
是不是下回来直接覆盖也一样

**Comment by Tsuk1ko** [comment]
@DazaiYuki 这，那上一个岂不是没测到

切完分支之后 git branch 可以看到带星号的就是当前分支

**Comment by DazaiYuki** [comment]
> C:\CQ-picfinder-robot>git branch
> \* master
>  remotes/origin/named-regexp-groups
现在状况是这样，所以其实……之前就没切到吗

**Comment by Tsuk1ko** [comment]
@DazaiYuki 你现在这个就是在master，没切

**Comment by DazaiYuki** [comment]
![image](https://user-images.githubusercontent.com/54615306/67680866-823b9480-f9cf-11e9-9fc9-2aeee085885d.png)
🤔这样就可以开始了吧 忽略中间那个 打错了

**Comment by Tsuk1ko** [comment]
@DazaiYuki 可以了

**Comment by DazaiYuki** [comment]
![image](https://user-images.githubusercontent.com/54615306/67681595-fdea1100-f9d0-11e9-9454-346dc3584693.png)

其实……可能还是没成。git branch以后还需要什么操作吗 我看星号在那就没做别的了
然后第一次npm i的时候报错了 log如下
[2019-10-28T13_10_22_570Z-debug.log](https://github.com/Tsuk1ko/CQ-picfinder-robot/files/3778799/2019-10-28T13_10_22_570Z-debug.log)
我没管又打了一遍就成了 然后用回旧的config也确实能开了

**Comment by DazaiYuki** [comment]
![image](https://user-images.githubusercontent.com/54615306/67683968-aac68d00-f9d5-11e9-97cd-ed8413375d7b.png)
我是没想到换个源就解决这个问题了（

**Comment by Tsuk1ko** [comment]
噗
