### ISSUE TITLE
npm start正常运行 pm2运行失败

### ISSUE THREAD

**Issue by Catkamakura** [Tsuk1ko/CQ-picfinder-robot#29]
**描述这个问题**
使用新分支remotes/origin/named-regexp-groups
node版本 8.16.2
npm start成功运行 但用pm2却会会报错，这是pm2的log
```
1|CQPF  | Error: Cannot find module '/root/CQ-picfinder- 
robot/node_modules/sqlite3/lib/binding/node-v67-linux-x64/node_sqlite3.node
1|CQPF  |     at Object.<anonymous> (/root/CQ-picfinder- 
robot/node_modules/sqlite3/lib/sqlite3.js:4:15)
```

使用ls看查目录：
`ls /root/CQ-picfinder-robot/node_modules/sqlite3/lib/binding`
显示文件为
`node-v57-linux-x64`

**如何复现**
复现步骤（如果能复现）
1. npm start， 成功链接，测试可以搜图
2. ctrl+c强制结束
3. npm run pm2start
3.5，测试搜图无反应
4. npm run pm2log

**截图及日志**
- 问题相关截图

- 日志内容（复制粘贴或截图，复制粘贴请包裹在代码块中）
![](http://ssr.mahiru.ml:8181/?/images/2019/10/29/rHbNAWQqCr/pm2log.png)
**平台**
 - 操作系统： CentOS 7 
 - Node 版本：8.16.2

**Comment by Tsuk1ko** [comment]
你是否有切换过或共存多个版本的 node

从这里看 pm2 需求的是 v67 (11.x.x) 的，而你目前使用的是 v57 (8.x.x) 的，可能是你的 pm2 是用 node 11.x.x 安装的而你现在更换了版本

可以尝试卸载 pm2 `npm uninstall pm2` 后重新安装 pm2，或者检查环境变量等
