### ISSUE TITLE
广播功能

### ISSUE THREAD

**Issue by liehun10086** [Tsuk1ko/CQ-picfinder-robot#30]
**功能描述**
管理者私聊机器人，机器人向加的所有群发送广播

**理由**
更新了色图的正则匹配，想发布更新内容给群友，但是一个群一个群的说又太麻烦了

**附加信息**
或许可以加入排除或包含群号的参数
例：
--msg=测试 --include=123123;456456  //只向123123 456456两个群发消息
--msg=测试 --exclude=789789              //向除了789789以外的所有群发消息
--msg=测试 --onlyAdmin                       //向所有是管理员的群发消息

**Comment by Tsuk1ko** [comment]
这一功能已经在 v2.11.0 实装，详细用法可以看[群发消息功能](https://github.com/Tsuk1ko/CQ-picfinder-robot/wiki/%E5%A6%82%E4%BD%95%E9%A3%9F%E7%94%A8#%E7%BE%A4%E5%8F%91%E6%B6%88%E6%81%AF)

由于怕打扰群友所以没做太多的测试，如果发现有 bug 可以重开该 issue 反馈一下
