### ISSUE TITLE
ascii2d检索失败

### ISSUE THREAD

**Issue by Catkamakura** [Tsuk1ko/CQ-picfinder-robot#31]
**描述这个 bug**
这几天开始ascii2d不能正确使用

**如何复现**
复现步骤（如果能复现）
1. 发送[图片](https://qingchunyelang.tk/view/images/2019/11/05/gGEgM9xr/ascii2d_bug_pic.jpg)给qqbot
2. 机器人回复

> [57.37%] 「2010-02-21 00:38:20」/「雪華」
> 
> https://drawr.net/show.php?id=1215688

二次回复：

> 相似度[57.37%]过低，如果这不是你要找的图，那么可能：确实找不到此图/图为原图的局部图/图清晰度太低/搜索引擎尚未同步新图
> 自动使用 ascii2d 进行搜索

接着回复：
```
ascii2d 色合検索
「<!DOCTYPE html><html lang="ja"><head>
<meta charset="utf-8">
<meta content="width=device-width initial-scale=1.0 user-scalable=1" name="viewport">
<title>二次元画像詳細検索</title>
<link rel="shortcut icon" type="image/x-icon" href="/assets/favicon-461e7af86f6c1a73f716cf8c729e65d6164851b66470932d01ef928ebbaed6ba.ico">
<link rel="stylesheet" media="screen" href="/assets/application-2c633823260f3a7ffd5e0b0751a46eac6450fa496435e8e260bdd19948c3fa6a.css" data-turbolinks-track="true">
<script src="/assets/application-fe719779fd1564d7386c41ccb804cbb69e13390ef4c3a655255a53c915a849bc.js" data-turbolinks-track="true"></script>

<meta name="csrf-param" content="authenticity_token">
<meta name="csrf-token" content="SIj0b8C4FkL31vcaWQMP6CU9lH7w/x0TmNue9LPVHN+F1S1uwjQaQ0wNc0+UgTV4dSLdphPakmYx21s27+bcoA==">
</head>
<body>
<div class="container">
<header class="navbar navbar-static-top" id="header" role="banner">
<div class="clearfix">
<div class="row">
<a class="hidden-md-up nav-item nav-link navbar-brand" href="/">二次元画像詳細検索</a>
<button class="hidden-md-up navbar-toggler pull-xs-right" data-target="#menu-bar" data-toggle="collapse" type="button">
<span class="small navbar-menu">目次</span>
</button>
</div>
<div class="row">
<div class="collapse navbar-toggleable-sm" id="menu-bar">
<ul class="nav navbar-nav pull-md-right">
<li class="nav-item">
<a class="nav-link" href="/readme">説明</a>
</li>
<li class="nav-item">
<a class="nav-link" href="/recently">最近の検索</a>
</li>
<li class="nav-item">
<a class="nav-link" href="/ranking/daily">ランキング</a>
</li>
<li class="nav-item dropdown">
<a aria-expanded="false" class="dropdown-toggle nav-link" data-toggle="dropdown" href="#" role="button">ツール</a>
<div class="dropdown-menu">
<a class="dropdown-item" href="https://chrome.google.com/webstore/detail/dlnbkfiafmkajgbhpdfmkeljamdlfelo" rel="noopener" target="_blank">Chrome拡張</a>
<div class="dropdown-divider"></div>
<a class="dropdown-item" href="https://addons.mozilla.org/ja/firefox/addon/256705/" rel="noopener" target="_blank">Firefox拡張</a>
<div class="dropdown-divider"></div>
<a class="dropdown-item" href="http://www.ascii2d.net/safari/Ascii2dImageSearch.safariextz" target="_blank">Safari拡張</a>
</div>
</li>
<li class="nav-item dropdown">
<a aria-expanded="false" class="dropdown-toggle nav-link" data-toggle="dropdown" href="#" role="button">連絡先</a>
<div class="dropdown-menu">
<a class="dropdown-item" href="http://jbbs.livedoor.jp/computer/42759/" rel="noopener" target="_blank">したらば掲示板</a>
<div class="dropdown-divider"></div>
<a class="dropdown-item" href="https://twitter.com/ascii2d" rel="noopener" target="_blank">twitter</a>
<div class="dropdown-divider"></div>
<a class="dropdown-item" href="mailto:webmaster@ascii2d.net">webmaster@ascii2d.net</a>
</div>
</li>
</ul>
</div>
</div>
</div>
</header>


<div class="top-page">
<h2 class="text-xs-center m-t-2 hidden-xs-down">二次元画像詳細検索</h2>
<form class="text-xs-center m-t-2" action="/search/uri" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓"><input type="hidden" name="authenticity_token" value="hglfUI+32TMeGRdc/RREFdmStjWfYWy70d7DUEIrXNFLVIZRjTvVMqXCkwkwln6FiY3/7XxE48543gaSHhicrg=="><h6>インターネットに画像がある場合</h6>
<div class="row m-t-2">
<div class="col-sm-3 hidden-xs-down"></div>
<div class="form-group col-sm-5 col-xs-12">
<input class="form-control" id="uri-form" name="uri" placeholder="画像のURL" type="url">
</div>
<div class="col-sm-1 col-xs-12">
<button class="btn btn-secondary" name="search" type="submit">検索</button>
</div>
<div class="col-sm-3 hidden-xs-down"></div>
</div>
</form><form id="file_upload" class="text-xs-center m-t-1" enctype="multipart/form-data" action="/search/file" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓"><input type="hidden" name="authenticity_token" value="Pu744XHSJs0p3d83WDmJvTPkBkxpNS7kuPLxWgr5/0HzsyHgc14qzJIGW2KVu7MtY/tPlIoQoZER8jSYVso/Pg=="><h6>画像ファイルを持っている場合</h6>
<div class="row m-t-2">
<div class="col-sm-3 hidden-xs-down"></div>
<div class="form-group col-sm-5 col-xs-12">
<input class="form-control" id="file-form" name="file" placeholder="画像のパス" type="file">
</div>
<div class="col-sm-1 col-xs-12">
<button class="btn btn-secondary" name="search" type="submit">検索</button>
</div>
<div class="col-sm-3 hidden-xs-down"></div>
</div>
</form></div>

</div>


</body></html>」/「null」

undefined
```
3. 输入 xxx
4. 出现 bug

**期望现象**
如果没 bug，本来应该得到什么结果

**截图及日志**
- 问题相关截图
![markdown](https://qingchunyelang.tk/view/images/2019/11/05/Ttpn8YHv/ascii2dBug.png "markdown")

**平台**
 - 操作系统：CentOS 7 
 - Node 版本：8.16.2

**Comment by Tsuk1ko** [comment]
这个问题比较迷，以前也有其他人反馈偶现过，不知道是什么原因导致 acii2d 没有搜索成功所以返回了主页，导致 html 无法被正确解析

目前并没有办法从根源上修复这个 bug，不清楚复现具体条件，并且也有可能是 ascii2d 访问QQ图片链接时存在什么偶发问题

目前能做的改动只有当出现这种情况时返回搜索失败的提示，而不再是这一长串 html

![image](https://user-images.githubusercontent.com/24877906/68144615-090fe480-ff6f-11e9-8b6c-bdb2b99c542c.png)

**Comment by shitianshiwa** [comment]
反馈一个偶发持续近一天的事件（现在能用，没有什么问题）
是在Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-66-generic x86_64) 里的酷Q官方的docker运行的
https://github.com/CoolQ/docker-wine-coolq
node版本v12.12.0，npm版本6.12.0？（近期版本有动过,在12.12.0至12.13.0之间摆动）
当时服务器里docker容器里的火狐浏览器可以用Ascii2d搜索图片
2019-10-27 18:54:39 [error] Ascii2d
Error: Request failed with status code 502
    at createError (/home/user/coolq/picfinder/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/user/coolq/picfinder/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/user/coolq/picfinder/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:215:7)
    at IncomingMessage.EventEmitter.emit (domain.js:476:20)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  config: {
    url: 'https://ascii2d.net/search/url/https%3A%2F%2Fc2cpicdw.qpic.cn%2Foffpic_new%2F1482169367%2F%2F933ca224-1f58-41aa-b5bb-7554c86bacb3%2F0%3Fvuin%3D748400683%26amp%3Bterm%3D2',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.19.0'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    validateStatus: [Function: validateStatus],
    data: undefined
  },
  request: ClientRequest {
    _events: [Object: null prototype] {
      socket: [Function],
      abort: [Function],
      aborted: [Function],
      error: [Function],
      timeout: [Function],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 6,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      _SNICallback: null,
      servername: 'ascii2d.net',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 9,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'ascii2d.net',
      _readableState: [ReadableState],
      readable: true,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular],
      [Symbol(res)]: [TLSWrap],
      [Symbol(asyncId)]: 115,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    connection: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      _SNICallback: null,
      servername: 'ascii2d.net',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 9,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'ascii2d.net',
      _readableState: [ReadableState],
      readable: true,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular],
      [Symbol(res)]: [TLSWrap],
      [Symbol(asyncId)]: 115,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    _header: 'GET /search/url/https%3A%2F%2Fc2cpicdw.qpic.cn%2Foffpic_new%2F1482169367%2F%2F933ca224-1f58-41aa-b5bb-7554c86bacb3%2F0%3Fvuin%3D748400683%26amp%3Bterm%3D2 HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'User-Agent: axios/0.19.0\r\n' +
      'Host: ascii2d.net\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _onPendingData: [Function: noopPendingOutput],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 1,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      maxCachedSessions: 100,
      _sessionCache: [Object]
    },
    socketPath: undefined,
    method: 'GET',
    path: '/search/url/https%3A%2F%2Fc2cpicdw.qpic.cn%2Foffpic_new%2F1482169367%2F%2F933ca224-1f58-41aa-b5bb-7554c86bacb3%2F0%3Fvuin%3D748400683%26amp%3Bterm%3D2',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      readable: false,
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [TLSSocket],
      connection: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 502,
      statusMessage: 'Gateway Error',
      client: [TLSSocket],
      _consuming: true,
      _dumped: false,
      req: [Circular],
      responseUrl: 'https://ascii2d.net/search/url/https%3A%2F%2Fc2cpicdw.qpic.cn%2Foffpic_new%2F1482169367%2F%2F933ca224-1f58-41aa-b5bb-7554c86bacb3%2F0%3Fvuin%3D748400683%26amp%3Bterm%3D2',
      redirects: []
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    _redirectable: Writable {
      _writableState: [WritableState],
      writable: true,
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _options: [Object],
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function],
      _currentRequest: [Circular],
      _currentUrl: 'https://ascii2d.net/search/url/https%3A%2F%2Fc2cpicdw.qpic.cn%2Foffpic_new%2F1482169367%2F%2F933ca224-1f58-41aa-b5bb-7554c86bacb3%2F0%3Fvuin%3D748400683%26amp%3Bterm%3D2'
    },
    [Symbol(kNeedDrain)]: false,
    [Symbol(isCorked)]: false,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'user-agent': [Array],
      host: [Array]
    }
  },
  response: {
    status: 502,
    statusText: 'Gateway Error',
    headers: {
      connection: 'close',
      'content-length': '11',
      server: 'h2o/2.3.0-beta1',
      'content-type': 'text/plain; charset=utf-8',
      'strict-transport-security': 'max-age=31536000'
    },
    config: {
      url: 'https://ascii2d.net/search/url/https%3A%2F%2Fc2cpicdw.qpic.cn%2Foffpic_new%2F1482169367%2F%2F933ca224-1f58-41aa-b5bb-7554c86bacb3%2F0%3Fvuin%3D748400683%26amp%3Bterm%3D2',
      method: 'get',
      headers: [Object],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      adapter: [Function: httpAdapter],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      validateStatus: [Function: validateStatus],
      data: undefined
    },
    request: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      connection: [TLSSocket],
      _header: 'GET /search/url/https%3A%2F%2Fc2cpicdw.qpic.cn%2Foffpic_new%2F1482169367%2F%2F933ca224-1f58-41aa-b5bb-7554c86bacb3%2F0%3Fvuin%3D748400683%26amp%3Bterm%3D2 HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/0.19.0\r\n' +
        'Host: ascii2d.net\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      path: '/search/url/https%3A%2F%2Fc2cpicdw.qpic.cn%2Foffpic_new%2F1482169367%2F%2F933ca224-1f58-41aa-b5bb-7554c86bacb3%2F0%3Fvuin%3D748400683%26amp%3Bterm%3D2',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      _redirectable: [Writable],
      [Symbol(kNeedDrain)]: false,
      [Symbol(isCorked)]: false,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: 'I/O timeout'
  },
  isAxiosError: true,
  toJSON: [Function]
}

**Comment by Tsuk1ko** [comment]
出现这种问题时可以尝试把图片二次截图后再发送

因为从QQ得到的图片链接是有时效的，如果你发送的不是新图片就有可能得到过期的链接，ascii2d 就无法取得图片
