### ISSUE TITLE
我在docker环境下  私聊正常，群没反应。

### ISSUE THREAD

**Issue by chenxuxin188** [Tsuk1ko/CQ-picfinder-robot#34]
后台能现实色图姬往群里发消息了，但是实际上群里什么都没看到。

**Comment by chenxuxin188** [comment]
![QQ截图20191215034933](https://user-images.githubusercontent.com/30059986/70853822-0c8f7780-1eee-11ea-91bd-4b83cb888359.png)
这个是后台的日志

**Comment by Tsuk1ko** [comment]
请养成先仔细读文档再提问题的习惯

https://github.com/Tsuk1ko/CQ-picfinder-robot/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

https://github.com/Tsuk1ko/CQ-picfinder-robot/wiki/%E9%99%84%E5%8A%A0%E5%8A%9F%E8%83%BD#setu

**Comment by chenxuxin188** [comment]
> 请养成先仔细读文档再提问题的习惯
> 
> https://github.com/Tsuk1ko/CQ-picfinder-robot/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
> 
> https://github.com/Tsuk1ko/CQ-picfinder-robot/wiki/%E9%99%84%E5%8A%A0%E5%8A%9F%E8%83%BD#setu

所以这只是机器人才会有的问题吗     我自己的QQ走我VPS的代理还是能发群消息的。

**Comment by Tsuk1ko** [comment]
你也看到了日志中是显示有发出消息的，这说明`本项目程序->cq-http->酷Q`这条路径上不存在问题，剩下的就是`酷Q->QQ->用户`这条路径，可以猜到的就是在`QQ->用户`时被 tx 屏蔽

我在 wiki 中所写的屏蔽的机制只是依据我自己的体验经历推断出的规律，有什么其他的限制就不得而知了

**Comment by chenxuxin188** [comment]
> 你也看到了日志中是显示有发出消息的，这说明`本项目程序->cq-http->酷Q`这条路径上不存在问题，剩下的就是`酷Q->QQ->用户`这条路径，撤回错误说明这条消息实际上没有留存在QQ的服务器上，可以猜想是被 tx 屏蔽了
> 
> 我在 wiki 中所写的屏蔽的机制只是依据我自己的体验经历推断出的规律，有什么其他的限制就不得而知了

好的谢谢，我在等几天看看吧。
