### ISSUE TITLE
艾特色图姬GKD的时候会回复两遍没色图

### ISSUE THREAD

**Issue by chenxuxin188** [Tsuk1ko/CQ-picfinder-robot#36]
**描述这个 bug**
正则表达当中keyword那一部分替换成艾特一个憨批或者竹竹自己，会回复找不到色图。如果艾特竹竹，会回复两次。

**如何复现**
复现步骤（如果能复现）
1.  竹竹发点 @某个憨批（或竹竹） 的色图

**期望现象**
回复找不到色图或者回复两次找不到色图。

**截图及日志**
截图之前没截图。。之前利用console测试过，艾特竹竹回复两遍是因为找不到色图的时候不会stopPropogation，groupmsg 和 groupmsgatme的commonhandler都会跑一次所以会发两遍。

**平台**
 - 操作系统：CentOS 7 
 - Node 版本：6.11.3

**附加内容**
为了更方冲出色图，正则方式有改过，比如
"^(?<keyword>.*?)GKD$"

有些憨批就会艾特姬器人来GKD
而且艾特某人的色图其实也挺有意思的……

我自己的解决方式是
在setu.js里
`const atMyselfReg = / *\[CQ:at,qq=[0-9]*\] */;`
一个艾特人的CQ码的正则表达

sendSetu的开头
`const tt = context.message.replace(atMyselfReg, '');`
`const setuRegExec = setuReg.exec(tt);`
然后找不到色图的时候也return true
在commonHandler里色图那部分IF条件里加了个

`e.stopPropagation();`

这样就可以

@某个憨批 发色图了。

话说大佬有赞助途径吗，感觉就这么白嫖代码还有大佬的色图库挺不好意思的。

**Comment by Tsuk1ko** [comment]
这个问题可以仅靠色图正则表达式解决，你可以看看正则表达式的零宽断言，可以做到不匹配某词，百度也有很多例子

**Comment by Tsuk1ko** [comment]
秉承着少要饭多发电不定期摸鱼怕充电催更的理念没有放码，实在想打钱可以去我博客随便点开一篇文章拉到下面有个赞赏
