### ISSUE TITLE
希望在色图库里添加画师 甘城なつき 的作品

### ISSUE THREAD

**Issue by chenxuxin188** [Tsuk1ko/CQ-picfinder-robot#37]
**功能描述**
色图库里添加画师 甘城なつき 的作品

**理由**
因为这个画师的猫娘好可爱啊！搜了好多次猫耳关键词的作品都没看到这位画师的作品_(:з」∠)_

**附加信息**
冲就完事了
https://www.pixiv.net/member.php?id=3036679

**Comment by chenxuxin188** [comment]
还有这几个_(:з」∠)_  知道大佬都是手动添加的，很麻烦很不容易
但是这些画师画得猫娘真的敲可爱我敲喜欢的_(:з」∠)_
里头多数是萝莉我相信大佬也会喜欢的_(:з」∠)_
https://www.pixiv.net/member.php?id=44234
https://www.pixiv.net/member.php?id=27591308
https://www.pixiv.net/member.php?id=2495644
https://www.pixiv.net/member.php?id=5445450
https://www.pixiv.net/member.php?id=6908845
https://www.pixiv.net/member.php?id=1113943

**Comment by chenxuxin188** [comment]
要是可以的话白丝的图再多一点_(:з」∠)_

**Comment by Tsuk1ko** [comment]
甘城なつき的是有的，这画师我老早就关注了，可能你运气不好🤣
另外，关键字可以用画师名

你推荐的其他画师我就心怀感激地收下了🌚

**Comment by chenxuxin188** [comment]
可能我运气真的比较差把_(:з」∠)_   我keyword用了甘城なつき出来的都是这位作者原先的画，新的都没看到过

**Comment by Tsuk1ko** [comment]
并不是所有的图都在里面，我只挑了有色点的一些，有些新的我可能也还没来得及加

另外我也有点想再弄多一个普通向的图库

**Comment by chenxuxin188** [comment]
其实不一定要很色，只要可爱就行了！
特别是可爱的萝莉，我最喜欢了！！！
图库GKD，我也可以帮忙找图的

**Comment by chenxuxin188** [comment]
那个……这些画师大佬都GET到了的话这个issue就先关了哈。。
