### ISSUE TITLE
无法退出搜图模式

### ISSUE THREAD

**Issue by onlymyflower** [Tsuk1ko/CQ-picfinder-robot#4]
使用搜图模式命令开启搜图模式后，竹竹搜就进入强迫症模式（不给图就一直回复），然后发送结束搜图模式指令后也无法退出搜图模式，依然要发送图（饥渴？），不停回复：必须要发送图片我才能帮你找噢_(:3」」
支持批量！。

**Comment by Tsuk1ko** [comment]
搜图模式是在群里使用的，你这应该是在私聊里吧
私聊仅有搜图功能，这个回复就是默认回复
