### ISSUE TITLE
大于一定体积时自动压缩

### ISSUE THREAD

**Issue by benx1n** [Tsuk1ko/CQ-picfinder-robot#40]
**功能描述**
希望可以添加图片大于一定阈值时自动压缩发送，和现有的全部压缩发送区分开

**理由**
启用反和谐后经常出现无法发送图片，查看了酷Q日志后可能原因是因为图片过大？（基本都是大于4M）
![Snipaste_2019-12-29_18-16-13](https://user-images.githubusercontent.com/48101337/71555444-58522d00-2a67-11ea-8edb-56c1aba02dd8.png)

**Comment by Tsuk1ko** [comment]
确定是图片过大引起的么，启用 size1200 的话就不会出现这种情况？

**Comment by benx1n** [comment]
是的，启动size1200就不会出现
而且统计了会出现这种报错的图片都是大于4M的
还有一个问题就是启用反和谐后响应会变慢是正常情况吗？

**Comment by shitianshiwa** [comment]
这个issues大概可以回答为什么需要压缩图片文件体积
使用CQ码发图片的时候图片大小不能超过4M
https://github.com/richardchien/coolq-http-api/issues/231

**Comment by Tsuk1ko** [comment]
@shitianshiwa 了解了

因为反和谐用 canvas 处理了图片，比直接发慢是肯定的，我没有实际统计过处理耗时，在开 size1200 的情况下体感没有多大区别

**Comment by Tsuk1ko** [comment]
@shitianshiwa v2.11.1 实装了

**Comment by shitianshiwa** [comment]
> @shitianshiwa v2.11.1 实装了

了解

**Comment by benx1n** [comment]
收到 那我关闭issue了

**Comment by benx1n** [comment]
更新后问题依然存在= =

**Comment by Tsuk1ko** [comment]
@shitianshiwa @benx1n 我傻了，功能写好了结果没去用（

已经修复，再拉下最新代码

**Comment by benx1n** [comment]
> @shitianshiwa @benx1n 我傻了，功能写好了结果没去用（
> 
> 已经修复，再拉下最新代码

收到，测试后还未出现吞图，辛苦大大了
