### ISSUE TITLE
a2d无法使用

### ISSUE THREAD

**Issue by SakuraSauce** [Tsuk1ko/CQ-picfinder-robot#41]
**描述这个 bug**
rt
无论是相似度过低，自动使用 ascii2d 进行搜索。还是用--a2d参数搜索，都没有回应。
**如何复现**
复现步骤（如果能复现）
1. 去 xxx
2. 点击 xxx
3. 输入 xxx
4. 出现 bug
1. 任何a2d请求都没有回应
**期望现象**
如果没 bug，本来应该得到什么结果
通过a2d获得更好的精确度
**截图及日志**
- 问题相关截图
- 日志内容（复制粘贴或截图，复制粘贴请包裹在代码块中）
https://s4.teriri.net.cn/CQ.txt
**平台**
 - 操作系统：例如 Windows 10 / Ubuntu 16.04 / CentOS 7 
Windows server 2012 R2
 - Node 版本：x.x.x
10.16.0
**附加内容**
先生，还有什么要补充的吗

**Comment by Tsuk1ko** [comment]
请更新到最新版本，ascii2d 对 UA 做了检测

另外，如果 ascii2d 使用过多可能会导致 ip 被其封禁，届时请自行想办法

**Comment by SakuraSauce** [comment]
> 请更新到最新版本，ascii2d对UA进行检测
> 
> 另外，如果ascii2d使用过多可能会导致ip被其封禁，届时请自行想办法

使用的是最新的2.11.0版本了。怎么判断ip被封禁？

**Comment by Tsuk1ko** [comment]
被封禁的话你在机器上开浏览器访问应该就会直接不给你访问

但我看你这里`'User-Agent': 'axios/0.19.0'`，新版是改了的

https://github.com/Tsuk1ko/CQ-picfinder-robot/blob/dd2c249e75668e3537a9e5293b4db60c28f40eac/modules/axiosProxy.js#L22-L27

你更新完之后有重启吗

**Comment by SakuraSauce** [comment]
> 被封禁的话你在机器上开浏览器访问应该就会直接不给你访问
> 
> 但我看你这里`'User-Agent': 'axios/0.19.0'`，新版是改了的
> 
> https://github.com/Tsuk1ko/CQ-picfinder-robot/blob/dd2c249e75668e3537a9e5293b4db60c28f40eac/modules/axiosProxy.js#L22-L27
> 
> 你更新完之后有重启吗

服务器上的浏览器能正常打开日志里的链接https://github.com/SakuraSauce/photolink/blob/master/CQ/server.jpg  
QQ里却无回应https://github.com/SakuraSauce/photolink/blob/master/CQ/QQ.png  
我更新都是下载新的版本重新npm i，然后把旧的配置文件复制粘贴过去，是这个的原因吗？

**Comment by Tsuk1ko** [comment]
应该不是，那就很迷，因为我这边是有正确使用 UA 的，问了下我朋友也没问题

**Comment by SakuraSauce** [comment]
> 应该不是，那就很迷，因为我这边是有正确使用 UA 的，问了下我朋友也没问题

好吧喵😂

**Comment by SakuraSauce** [comment]
> 被封禁的话你在机器上开浏览器访问应该就会直接不给你访问
> 
> 但我看你这里`'User-Agent': 'axios/0.19.0'`，新版是改了的
> 
> https://github.com/Tsuk1ko/CQ-picfinder-robot/blob/dd2c249e75668e3537a9e5293b4db60c28f40eac/modules/axiosProxy.js#L22-L27
> 
> 你更新完之后有重启吗

问一下，error 500就是被屏蔽了吗？

**Comment by Tsuk1ko** [comment]
我有一个被屏蔽的是直接返回 404 的，另外还存在 UA 检测，我目前只知道这些

**Comment by SakuraSauce** [comment]
> 我有一个被屏蔽的是直接返回 404 的，另外还存在 UA 检测，我目前只知道这些

真奇怪，后来又能用ascii2d了，可是刚用2天，又显示"ascii2d 搜索失败"，后台是error 500。

**Comment by Tsuk1ko** [comment]
总之如果你在机器上直接用浏览器能正常访问其 API 就说明没被封禁（看 [readme](https://ascii2d.net/readme) 右侧的那个实验性 API），图片 URL 可以通过给机器人发图带`--get-url`参数获得

如果直接访问没问题，剩下的可能还是 UA 问题，检查你的错误日志，为什么你这里没生效我也不得而知了，实在不行的话本地起一个 nginx 来反代，设置 proxy header 来加上自己浏览器的 UA，改配置`ascii2dHost`来用本地反代

**Comment by SakuraSauce** [comment]
> 总之如果你在机器上直接用浏览器能正常访问其 API 就说明没被封禁（看 [readme](https://ascii2d.net/readme) 右侧的那个实验性 API），图片 URL 可以通过给机器人发图带`--get-url`参数获得
> 
> 如果直接访问没问题，剩下的可能还是 UA 问题，检查你的错误日志，为什么你这里没生效我也不得而知了，实在不行的话本地起一个 nginx 来反代，设置 proxy header 来加上自己浏览器的 UA，改配置`ascii2dHost`来用本地反代

把服务器重启过又好了，我怀疑是Windows 2012的问题。到时候装成centos试试看。

**Comment by Tsuk1ko** [comment]
@SakuraSauce 如果你不熟悉 docker 那一套和一些网络细节不建议用 linux 酷Q

**Comment by SakuraSauce** [comment]
> @SakuraSauce 如果你不熟悉 docker 那一套和一些网络细节不建议用 linux 酷Q

酷Q还是在Windows2012上，只是把这个CQ-picfinder-robot项目移动到别的Linux服务器上。(我有3台centos)HTTP插件支持从公网连接吧？

**Comment by Tsuk1ko** [comment]
@SakuraSauce 支持的，只要你记得确保端口开放以及配置填对就行
