### ISSUE TITLE
安装过程出现问题

### ISSUE THREAD

**Issue by ReninScarlet** [Tsuk1ko/CQ-picfinder-robot#42]
**描述这个 bug**
无论是挂vpn还是切换node版本还是yarn还是cnpm都会出现这两行提示无法下载的紫字，导致npm start报错

**如何复现**
复现步骤（如果能复现）
1. npm i
2. 出现 bug

**截图及日志**
- 问题相关截图
- 日志内容（复制粘贴或截图，复制粘贴请包裹在代码块中）
![image](https://user-images.githubusercontent.com/46163235/71980801-e1cde000-325b-11ea-940f-254235e550dd.png)
![image](https://user-images.githubusercontent.com/46163235/71980925-33766a80-325c-11ea-9805-403b2506ff34.png)
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.13.4
3 info using node@v10.18.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle cq-picfinder-robot@2.11.0~prestart: cq-picfinder-robot@2.11.0
6 info lifecycle cq-picfinder-robot@2.11.0~start: cq-picfinder-robot@2.11.0
7 verbose lifecycle cq-picfinder-robot@2.11.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle cq-picfinder-robot@2.11.0~start: PATH: C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Administrator\CQ-picfinder-robot\node_modules\.bin;C:\Python27\;C:\Python27\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\Yarn\bin\;C:\Program Files (x86)\nodejs\;C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Scripts\;C:\Users\Administrator\AppData\Local\Programs\Python\Python38\;C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\Scripts\;C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\Users\Administrator\AppData\Local\Yarn\bin;C:\Users\Administrator\AppData\Roaming\npm
9 verbose lifecycle cq-picfinder-robot@2.11.0~start: CWD: C:\Users\Administrator\CQ-picfinder-robot
10 silly lifecycle cq-picfinder-robot@2.11.0~start: Args: [ '/d /s /c', 'node index.js' ]
11 silly lifecycle cq-picfinder-robot@2.11.0~start: Returned: code: 1  signal: null
12 info lifecycle cq-picfinder-robot@2.11.0~start: Failed to exec start script
13 verbose stack Error: cq-picfinder-robot@2.11.0 start: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid cq-picfinder-robot@2.11.0
15 verbose cwd C:\Users\Administrator\CQ-picfinder-robot
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v10.18.0
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error cq-picfinder-robot@2.11.0 start: `node index.js`
22 error Exit status 1
23 error Failed at the cq-picfinder-robot@2.11.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
**平台**
 - 操作系统：Windows Server2019
 - Node 版本：10.16.0 12.14.0

**附加内容**
非计算机专业萌新，已经用尽了百度，csdn等方法……只能请教大佬了

**Comment by Tsuk1ko** [comment]
看日志是你当前网络无法直连 github 因此下载预编译二进制文件失败

如果你单纯挂的系统代理是没用的，因为命令行并不走系统代理，你需要用 sstap 之类的工具代理，或者尝试按下面的方法为 npm 设置代理

以本地端口为`1080`的小飞机为例

```bash
npm config set proxy http://127.0.0.1:1080
npm config set https-proxy http://127.0.0.1:1080
```

如果要取消

```bash
npm config delete proxy
npm config delete https-proxy
```

**Comment by ReninScarlet** [comment]
`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'canvas' ]
2 info using npm@6.13.4
3 info using node@v10.18.0
4 verbose npm-session 62e33c98ba5fb82b
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 timing npm Completed in 11381ms
8 error cb() never called!
9 error This is an error with npm itself. Please report this error at:
10 error <https://npm.community>
`
![image](https://user-images.githubusercontent.com/46163235/71985216-1003ed80-3265-11ea-8a56-7225456b099c.png)
我是不是哪里理解错了……

**Comment by ReninScarlet** [comment]
我的小飞机的确是1080端口的

**Comment by Tsuk1ko** [comment]
重新 clone 一份再试，或者`npm cache clean -f`

都不行的话还是取消代理然后用 sstap 吧

**Comment by ReninScarlet** [comment]
解决不了，我选择等到期了换台墙外的服务器……

**Comment by shitianshiwa** [comment]
> 解决不了，我选择等到期了换台墙外的服务器……

-我关于这个问题的实际解决方法是，直接在墙外的服务器里安装npm，然后把整个文件夹下载下来。
我用的QQ机器人是这个 
酷Q with .Net on Docker https://github.com/MerCuJerry/docker-wine-coolq-dotnet45-autoins 
在这个容器里面安装
----
-也许这个方法有用
https://github.com/Tsuk1ko/CQ-picfinder-robot/issues/27#issuecomment-546957475
npm config set registry https://registry.npm.taobao.org
npm config get registry

**Comment by ReninScarlet** [comment]
npm config set registry https://registry.npm.taobao.org我已经尝试过了，我觉得还是搞个墙外服务器比较靠谱

**Comment by Quan666** [comment]
你这个问题很好解决，我是国内阿里云，测试完美解决。
建议作者加到部署流程里面，解决办法在博客里
https://myelf.club/index.php/archives/186/

**Comment by Quan666** [comment]
> 你这个问题很好解决，我是国内阿里云，测试完美解决。
> 建议作者加到部署流程里面，解决办法在博客里
> https://myelf.club/index.php/archives/186/

才发现作者已经加了

**Comment by Tsuk1ko** [comment]
@Quan666 在你的文章中，为 cnpm 设置 registry 是多余的，cnpm 本质上就是 npm 设置了淘宝镜像的 registry 和 disturl 的一个 alias，在 https://npm.taobao.org/ 有说明

之前我提供的建议漏掉了 disturl，因此 fallback-to-build 的时候依然使用了官方镜像，后来我已经在 wiki 中补充了，同理使用 yarn 也可以设置 registry 和 disturl

**Comment by Quan666** [comment]
> @Quan666 在你的文章中，为 cnpm 设置 registry 是多余的，直接`cnpm i`即可，cnpm 本质上就是 npm 设置了淘宝镜像的 registry 和 disturl 的一个 alias，在 https://npm.taobao.org/ 有说明
> 
> 之前我提供的建议漏掉了 disturl，因此 fallback-to-build 的时候依然使用了官方镜像，后来我已经在 wiki 中补充了，同理使用 yarn 也可以设置 registry 和 disturl

好的，感谢提醒

**Comment by ReninScarlet** [comment]
> 你这个问题很好解决，我是国内阿里云，测试完美解决。
> 建议作者加到部署流程里面，解决办法在博客里
> https://myelf.club/index.php/archives/186/

我之前尝试过了，但一直提示canvas 404不能下载
