### ISSUE TITLE
OCR功能不工作

### ISSUE THREAD

**Issue by Lancercmd** [Tsuk1ko/CQ-picfinder-robot#44]
可以使用 --update-akhr 成功更新akhr数据库

但不能用 --akhr 调用明日方舟公招计算器，bot不处理消息

也不能用 --ocr 调用OCR功能（通过baidubce），bot不处理消息，即使已填写正确的apiKey和secretKey

**Comment by Tsuk1ko** [comment]
@Lancercmd 贴一下错误日志

**Comment by Lancercmd** [comment]
npm start 和 pm2 logs 都没有错误提示，以下为实例截图

![Screenshot_20200120-094412_TeamViewer](https://user-images.githubusercontent.com/59906398/72692989-daff7100-3b69-11ea-8b68-8e869aa51086.jpg)
图一 选择了baidubce并已正确填写apiKey和secretKey

![Screenshot_20200120-094534_QQ](https://user-images.githubusercontent.com/59906398/72693015-fe2a2080-3b69-11ea-8b8c-298ed98d330e.jpg)
图二 在和bot的私聊内使用OCR功能

![Screenshot_20200120-094549_QQ](https://user-images.githubusercontent.com/59906398/72693044-1e59df80-3b6a-11ea-8744-b95e7c385b2c.jpg)
图三 消息直接被返回至关联账号并没有应答，表示bot没有处理这个消息

**Comment by Tsuk1ko** [comment]
@Lancercmd 那么是只有这个功能无法使用还是所有功能都无法使用？

私聊随便发点文字，有正常收到默认回复么

**Comment by Lancercmd** [comment]
@Tsuk1ko  只有OCR功能（以及依赖其运行的akhr公招计算器）不工作，同时含有 --akhr 或 --ocr 开关的消息不会回复默认消息

**Comment by Adricn** [comment]
我更惨..前缀”—”的指令只有限定搜索库的那几个才有效果，其他的会被视作一般消息，不带“—”的签到关键字也被视作一般消息...明明看脚本里没啥问题的..氦.. ΦωΦ

**Comment by Tsuk1ko** [comment]
> 我更惨..前缀”—”的指令只有限定搜索库的那几个才有效果，其他的会被视作一般消息，不带“—”的签到关键字也被视作一般消息...明明看脚本里没啥问题的..氦.. ΦωΦ

是`--`不是`—`啊，你怕不是输入法智能破折号了

**Comment by Adricn** [comment]
我把main.js的前缀识别改破折号了..也许是作死吧，我改回来看看，谢谢啦

**Comment by Tsuk1ko** [comment]
> 我把main.js的前缀识别改破折号了..也许是作死吧，我改回来看看，谢谢啦

是的，不能直接这样改的，因为大部分命令识别是直接用的 [minimist](https://www.npmjs.com/package/minimist)

**Comment by Adricn** [comment]
哈哈看来我还是太年轻..可以正常识别指令了，但有个新问题，百度OCR在字数超50左右的时候会在日志里显示已发送，我却接受不到，请问阁下有没有类似情况，感谢回复

**Comment by Tsuk1ko** [comment]
> 哈哈看来我还是太年轻..可以正常识别指令了，但有个新问题，百度OCR在字数超50左右的时候会在日志里显示已发送，我却接受不到，请问阁下有没有类似情况，感谢回复

多半是 tx 的某些限制，我也无能为力

**Comment by Adricn** [comment]
这样啊..谢谢啦，我再试试拆分开能不能发送吧……

**Comment by Adricn** [comment]
行吧....开个qq会员就可以了...emmm这真不是广告

**Comment by Lancercmd** [comment]
总之最后也没明白为什么用不了cqpf内的OCR。。在自己的Python项目内写了一个用了√
