### ISSUE TITLE
ascii2d搜索报错

### ISSUE THREAD

**Issue by gundami** [Tsuk1ko/CQ-picfinder-robot#45]
**描述这个 bug**
ascii2d搜索报错

**如何复现**
复现步骤（如果能复现）
低重合度图片搜索后ascii2d搜索报错

**期望现象**
出搜图结果

**截图及日志**

ascii2d 色合検索
由未知错误导致搜索失败

ascii2d 特徴検索
由未知错误导致搜索失败

**平台**
 - 操作系统： Ubuntu 18.04 
 - Node 版本：10.18.1

**Comment by Tsuk1ko** [comment]
该问题多半是你当前的 IP 被 ascii2d 封禁所致，请参考 #41 排查，如果确认是被封禁且你没有能力想出其它办法曲线救国，那我也救不了了

在下一版本我会加入 ascii2d 开关来关闭这一功能

**Comment by gundami** [comment]
我试过curl https://ascii2d.net是有反应的

**Comment by Tsuk1ko** [comment]
@gundami 可以提供一下错误日志么，在 log 文件夹内

**Comment by gundami** [comment]
只有pm2的logs，其他的log文件夹没找到

**Comment by Tsuk1ko** [comment]
都可，提供下 error 日志

**Comment by gundami** [comment]
error-0.log是空的，normal-0.log是
1/21/2020, 4:54:52 AM 连接中[/event]#1
1/21/2020, 4:54:52 AM 连接中[/api]#1
1/21/2020, 4:54:52 AM 连接成功[/event]#1
1/21/2020, 4:54:52 AM 连接成功[/api]#1

**Comment by Tsuk1ko** [comment]
@gundami 那不应该……

没错误日志的话没办法判断问题了

**Comment by Tsuk1ko** [comment]
大致知道原因了，把代码更新一下，然后出错的话应该就会输出错误日志了

**Comment by gundami** [comment]
https://pastebin.com/TMgnzuhe
这是错误报告

**Comment by Tsuk1ko** [comment]
OK，现在麻烦再更新一下看看错误日志

**Comment by gundami** [comment]
现在是
1/21/2020, 6:28:17 AM [error] ascii2d getDetail
[object Object]
1/21/2020, 6:28:17 AM [error] ascii2d getDetail
[object Object]
1/21/2020, 6:28:27 AM [error] ascii2d getDetail
[object Object]
1/21/2020, 6:28:27 AM [error] ascii2d getDetail
[object Object]

**Comment by Tsuk1ko** [comment]
我傻了，不好意思，再来一次

![AB69761B9625A72F3F9BF438758EFF26](https://user-images.githubusercontent.com/24877906/72780794-b931e700-3c5a-11ea-8aab-35185d6d1c7e.gif)

**Comment by gundami** [comment]
https://pastebin.com/9VJeRy00
错误报告

**Comment by Tsuk1ko** [comment]
这个问题目前的情况：

- URL 没问题
- UA 没问题
- 没有被封

但永远返回的却是首页 https://ascii2d.net/ 的内容，应该是被 302 过去的，不清楚 ascii2d 有什么机制

https://ascii2d.net/search/url/https%3A%2F%2Fc2cpicdw.qpic.cn%2Foffpic_new%2F2036150446%2F%2Fcc61a2c8-be56-403b-b34a-c756f1944cde%2F0%3Fterm%3D2

试着访问这个（开无痕），能不能出结果页，还是说会被跳回首页

**Comment by gundami** [comment]
电脑上直接访问可以，但是服务器上会跳到主页
https://pastebin.com/ZZWnDwe2

**Comment by Tsuk1ko** [comment]
服务器是刚开始用就这样还是后来才出现的情况

**Comment by gundami** [comment]
一开始就这样

**Comment by Tsuk1ko** [comment]
那很迷，在代码层面上暂时没办法解决了，可能是 IP 被针对了，也不知道具体机制原因，实在想用只能尝试配置`picfinder.proxy`

刚刚更新了下，[增加了两个配置项](https://github.com/Tsuk1ko/CQ-picfinder-robot/blob/master/CHANGELOG.md#1-21-v2112)用于控制是否自动使用 ascii2d，如果实在无法解决只能关一下了

**Comment by chenxuxin188** [comment]
可能是IP问题吧。。。我的ascii2d完全没问题。
