### ISSUE TITLE
请问一下能不能在本地Windows上面使用这个插件啊

### ISSUE THREAD

**Issue by ximoonpig** [Tsuk1ko/CQ-picfinder-robot#46]
**功能描述**
rt

**理由**
服务器内存不够，于是想在自己的另外一台挂机电脑上运行这个

**附加信息**
如果方便请教我一下下，不方便就算了，谢谢大佬

**Comment by Tsuk1ko** [comment]
CQ-picfinder-robot 可以和酷Q分开在不同的机器上运行，你只需要修改 CQ-picfinder-robot 配置中的`host`，让它连接另一台机器上的 cq-http 即可

这要求至少有一台服务器有公网，如果酷Q所在服务器有公网则很简单，确保服务器的安全组和防火墙放行`ws_port`端口即可（默认`6700`那个）；如果反过来，你可能需要自行使用 [frp](https://github.com/fatedier/frp) 之类的程序做个内网穿透

**Comment by ximoonpig** [comment]
谢谢
