### ISSUE TITLE
关于退出搜图模式

### ISSUE THREAD

**Issue by 666wcy** [Tsuk1ko/CQ-picfinder-robot#47]
无法退出搜图模式（重启的时候自己就开启了）
一直是发送图片就就查找
输入退出指令时就提示只能发送图片
请问这个是bug还是默认设计成这样

**Comment by Tsuk1ko** [comment]
搜图模式是群组内功能

私聊就是直接搜图，设计如此

**Comment by 666wcy** [comment]
好的，感谢解答
