### ISSUE TITLE
R18功能无法按keyword值搜索

### ISSUE THREAD

**Issue by DoneBootbloader** [Tsuk1ko/CQ-picfinder-robot#48]
**描述这个 bug**
rt在搜索R18涩图时候无法按照keyword的值进行准确搜索，只能识别出R18+色图。。

**如何复现**
复现步骤（如果能复现）
1. 去 xxx
2. 点击 xxx
3. 输入 xxx
4. 出现 bug

**期望现象**
如果没 bug，本来应该得到什么结果

**截图及日志**
- 问题相关截图
- 日志内容（复制粘贴或截图，复制粘贴请包裹在代码块中）

**平台**
 - 操作系统:Windows 10
 - Node 版本：11.10.0

**附加内容**
先生，还有什么要补充的吗

**Comment by Tsuk1ko** [comment]
你是否有自行修改过正则表达式？以及你的发言是什么？

总之我这里是没什么问题

![image](https://user-images.githubusercontent.com/24877906/75676213-c7483e00-5cc3-11ea-876c-11d5f3fe8c75.png)

另外，因为按关键字搜素是从库中模糊搜索得到的结果，有可能是作者名字/作品标题/标签中确实**包含**了你给出的关键字，但其语义与你给出的关键字不同

这点目前无法改进，毕竟没有按搜索引擎那么复杂的方面去设计，并且还涉及到多国语言
