### ISSUE TITLE
最新版2.11.10无法成功启动喵

### ISSUE THREAD

**Issue by SakuraChanNya** [Tsuk1ko/CQ-picfinder-robot#52]
**描述这个 bug**
最新版2.11.10无法成功启动，旧版本2.11.6无此问题喵

**如何复现**
复现步骤（如果能复现）
1. 输入npm run pn2start
2. 能正常显示绿色online
3. 但内部报错
4. 无法重启，显示waiting restart

**期望现象**
如果没 bug，本来应该得到什么结果
连接成功[/event]#1
连接成功[/api]#1
**截图及日志**
- 问题相关截图
- 日志内容（复制粘贴或截图，复制粘贴请包裹在代码块中）
```
0|CQPF     |             let obj = new ();
0|CQPF     |                            ^
0|CQPF     |
0|CQPF     | SyntaxError: Unexpected token )
0|CQPF     |     at new Script (vm.js:83:7)
0|CQPF     |     at Generator.next (<anonymous>)
0|CQPF     |     at Object.Module._extensions..js (internal/modules/cjs/loader.j
s:787:10)
0|CQPF     | C:\Users\Administrator\Desktop\Git\CQ-picfinder-robot-2.11.10\node_
modules\tencentcloud-sdk-nodejs\tencentcloud\ecm\v20190719\models.js:2505
0|CQPF     |             let obj = new ();
0|CQPF     |                            ^
0|CQPF     |
0|CQPF     | SyntaxError: Unexpected token )
0|CQPF     |     at new Script (vm.js:83:7)
0|CQPF     |     at Generator.next (<anonymous>)
0|CQPF     |     at Object.Module._extensions..js (internal/modules/cjs/loader.j
s:787:10)
```
**平台**
 - 操作系统：例如 Windows 10 / Ubuntu 16.04 / CentOS 7 
 - Node 版本：x.x.x
操作系统：Windows Server 2012 R2
Node 版本：v10.16.0
**附加内容**
先生，还有什么要补充的吗

**Comment by Tsuk1ko** [comment]
是不是更新之后忘了`npm i`？

**Comment by SakuraChanNya** [comment]
> 是不是更新之后忘了`npm i`？

没有忘记喵，执行过npm i --registry=https://registry.npm.taobao.org --disturl=https://npm.taobao.org/dist 了
![image](https://user-images.githubusercontent.com/29686930/77030612-1b4c6580-69da-11ea-841b-66bbc34f5af9.png)

**Comment by Tsuk1ko** [comment]
尝试把`package.json`里`tencentcloud-sdk-nodejs`的版本改成`^3.0.118`，然后再`npm i`试试？

**Comment by SakuraChanNya** [comment]
> 尝试把`package.json`里`tencentcloud-sdk-nodejs`的版本改成`^3.0.118`，然后再`npm i`试试？

修改之后重新npm i，可以正常启动了喵

**Comment by Tsuk1ko** [comment]
妥，下次如果要更新代码的话，`git pull`之前执行一下`git reset --hard`

**Comment by SakuraChanNya** [comment]
> 妥，下次如果要更新代码的话，`git pull`之前执行一下`git reset --hard`

好的喵
