### ISSUE TITLE
反和谐后因图片过大而发送失败问题

### ISSUE THREAD

**Issue by xb2016** [Tsuk1ko/CQ-picfinder-robot#53]
**复现**
在启用反和谐功能的条件下发送图片 https://i.pximg.net/img-original/img/2020/03/09/14/18/34/80000352_p0.jpg

**原因**
1. 这张图片为 jpg 格式，且图片大小小于 3MB，所以不会触发 toMaster1200
2. 在经过反和谐之后，输出格式变为 png，且大小为 5MB，导致发送失败

**建议**
1. 图片大小判断放在发送前
2. `canvas.toDataURL` 输出指定为 `image/jpeg`

**最后**
感谢大佬的插件！

**Comment by Tsuk1ko** [comment]
了解，感谢报告问题

**Comment by Tsuk1ko** [comment]
已修复，现在会在反和谐后检测大小，超标的再用 master1200

jpg quality 经过对比测试选择了`0.97`🤔

**Comment by xb2016** [comment]
我随便抽了个 0.95 感觉都差不多 能冲就行🤔
