### ISSUE TITLE
无法使用whatanime搜索

### ISSUE THREAD

**Issue by JohnSmith868** [Tsuk1ko/CQ-picfinder-robot#54]
**描述这个 bug**
rt

**如何复现**
复现步骤（如果能复现）
1. 私聊状态发送图片--anime
2. 机器人回复第一个结果
SauceNAO [37.05%] AniDB
根据设置，低相似度结果的缩略图不予显示
https://anidb.net/anime/4226
第二个结果
相似度[37.05%]过低，如果这不是你要找的图，那么可能：确实找不到此图/图为原图的局部图/图清晰度太低/搜索引擎尚未同步新图
第三个结果
搜索失败惹 QAQ
有可能是服务器网络爆炸，请重试一次

3. 去服务器查看log，看到[error]

**期望现象**
应该出现whatanime的结果

**截图及日志**
- 问题相关截图
![image](https://user-images.githubusercontent.com/43031531/78243206-ee3d9e00-7515-11ea-89c3-84708854d456.png)

- 日志内容![image](https://user-images.githubusercontent.com/43031531/78243124-c3534a00-7515-11ea-9574-cd1e724a3d46.png)

**平台**
 - 操作系统：Ubuntu 16.04 
 - Node 版本：10.x

**附加内容**
无

**Comment by Tsuk1ko** [comment]
已修复，请更新代码试试

**Comment by JohnSmith868** [comment]
好的，幸苦大佬了
