### ISSUE TITLE
建议程序异常退出前给账号管理员发个信息提醒

### ISSUE THREAD

**Issue by dollarser** [Tsuk1ko/CQ-picfinder-robot#55]
**异常退出提醒**
rt

**理由**
让他去世前说一下自己快挂了，这个不知道能不能办到。希望能够实现。感觉程序经常异常退出，比如一旦某次查询网络连接失败，或者结果返回有问题。程序就直接挂掉了，希望进一步提高异常处理的问题，让程序更健壮点，或能通知账号管理员。

**附加信息**
先生，还有什么要补充的吗

**Comment by Tsuk1ko** [comment]
并不能。。。打个不恰当的比方这就相当于让一个已经猝死的人爬起来打120😂

**Comment by Tsuk1ko** [comment]
另外用 pm2 守护就是为了解决异常退出的问题，使程序可以自动重启，并且每当启动时会给 admin 私聊“已连接”，这也是一个提醒信息

我自己用了这么久了都没在平时遇到会导致程序崩溃的过严重错误，普通的网络错误都会被捕获记录在日志中而不会导致程序崩溃
