### ISSUE TITLE
启动后卡死，无消息返回

### ISSUE THREAD

**Issue by Adpex** [Tsuk1ko/CQ-picfinder-robot#56]
**描述这个 bug**
按照wiki里的部署流程走完之后，使用cnpm start，前端返回启动的消息，但之后就卡死

**如何复现**
复现步骤（如果能复现）
执行cnpm start或cnpm run pm2start 后卡死

**期望现象**
能正常走通

**截图及日志**
- 问题相关截图
![image](https://user-images.githubusercontent.com/16286708/79995095-5cf49280-84e9-11ea-9b5e-71c53d7b7037.png)

- 日志内容（复制粘贴或截图，复制粘贴请包裹在代码块中）
![image](https://user-images.githubusercontent.com/16286708/80001916-8a453e80-84f1-11ea-8d98-dc6ccafa290b.png)

**平台**
 - 操作系统：Windows server 2012R2 1核2G
 - Node 版本：12.16.2

**附加内容**
是否服务器配置不够？

附配置文件截图（未配置数据库）
![image](https://user-images.githubusercontent.com/16286708/80001555-130faa80-84f1-11ea-956d-c9e517d5221c.png)

**Comment by Tsuk1ko** [comment]
这没问题呀，不是卡死，连接成功就说明连上了，之后除非出错，不会再输出日志

**Comment by Adpex** [comment]
> 这没问题呀，不是卡死，连接成功就说明连上了，之后除非出错，不会再输出日志

嗯，我现在遇到的问题就是连上了但是不工作。。。具体就是无论怎么发指令都是没有返回。。

**Comment by Adpex** [comment]
问题解决了，私聊可以返回，估计是群聊设置的问题，打扰了！

**Comment by Tsuk1ko** [comment]
https://github.com/Tsuk1ko/CQ-picfinder-robot/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
