### ISSUE TITLE
群聊没有响应但私聊正常

### ISSUE THREAD

**Issue by alesky** [Tsuk1ko/CQ-picfinder-robot#58]
搜图和来点色图功能群聊没有响应，私聊正常
不知道该怎么 debug 了，看 npm start 和 cq-http 的日志似乎没发现有什么问题

附图：
![TIM图片20200429182411](https://user-images.githubusercontent.com/1336039/80585954-c1ae7080-8a46-11ea-810a-e7fb4237c114.jpg)
![TIM图片20200429182420](https://user-images.githubusercontent.com/1336039/80585964-c541f780-8a46-11ea-9be1-de70b0313246.jpg)
![image](https://user-images.githubusercontent.com/1336039/80586328-5e710e00-8a47-11ea-8bcd-0f1db191407b.png)
![2020-04-29_18-22-59](https://user-images.githubusercontent.com/1336039/80585971-c7a45180-8a46-11ea-9a11-b7686f1fafe4.png)
![2020-04-29_18-23-22](https://user-images.githubusercontent.com/1336039/80585975-ca06ab80-8a46-11ea-955f-375cc18cc23e.png)

运行环境：CoolQ Pro on Docker, Ubuntu 18.04 Kernel:  4.15.0-88-generic
Node 版本：12.16.1
npm 版本： 6.13.4
node 版本由 nvm 管理

**Comment by Tsuk1ko** [comment]
我寻思我不仅 wiki 白写了，issue template 也白写了

**Comment by alesky** [comment]
您好，很抱歉打扰您的时间，不过我在wiki中并未找到与我的问题相关内容。
只有一个类似情况：

Q：有时候在群组中机器人没有反应，但酷Q日志中显示是发出去了

我这里是酷Q日志里也没有发送成功的消息，只有cq-http日志中有把请求转发给picfinder项目的内容（按照我的理解这说明程序与cqhttp连接是正常的），并且picfinder日志中并没有是否收到请求的记录，config.json中只有搜图的debug开关。

Wiki的常见问题页面中其他问题并没有涵盖我这的情况。

**Comment by Tsuk1ko** [comment]
抱歉，外出途中看的不够仔细

拉取的是最新的代码么，之前某个晚上我更新的时候有一版曾经有 bug

**Comment by alesky** [comment]
是的， master 分支最新的

![image](https://user-images.githubusercontent.com/1336039/80589569-05a47400-8a4d-11ea-816c-61cd8e2c3775.png)

**Comment by Tsuk1ko** [comment]
是否有试过在 win 上面能否复现

看日志的话，程序有尝试撤回，说明 setu 流程是正常触发的了，但 cq-http 日志上没有调用 send_group_msg，并且程序日志中有个 404 错误

这个 404 错误应该就是 node-cq-websocket 框架请求 cq-http 的 API 的时候产生的，但私聊没问题，很怪

要 debug 的话，我建议在下面这个函数的开头`console.log(context)`，提供一下发送群组消息时的 log 内容

https://github.com/Tsuk1ko/CQ-picfinder-robot/blob/fcaa72ea433e92fe40f0e4ef89a69386955af641/main.js#L549-L575

**Comment by Tsuk1ko** [comment]
顺便删掉了一句遗留的测试代码……可以更新一下

**Comment by alesky** [comment]
尝试撤回的那条是私聊的 setu ，手机的图是截的比较早的所以还没撤回（我设置的是 90s ）；那个撤回虽然报错了但实际上是撤回了的，可能是 酷Q 那边的问题？

晚些时候我会找一台 Windows 机器测试，目前在加班并且没配过 Window s的 cqhttp 插件（…

另外函数开头加 `console.log` 是要加在哪里，是把函数的 `context` 参数替换成 `console.log(context)` 吗？（不会 js 非常尴尬

**Comment by Tsuk1ko** [comment]
这样，那那个撤回报错是没影响的，酷Q确实有这个 bug

那就怀疑是根本没收到群聊事件了，可以试下直接在群里里 @ 机器人，如果没出默认回复的话八成就是

真是的话我也没辙了，没遇过这种问题，总之肯定不是程序问题（甩锅

**Comment by Tsuk1ko** [comment]
话说你没有一直开着 debug 模式吧，debug 下是不会响应群内普通消息的，只会响应群 @ 消息……

**Comment by alesky** [comment]
了解了，原来是这样，是我傻逼了…就是开着 debug 的原因了。
关掉之后能看到log里有收到消息的记录和酷Q有下发消息了，然后这次是被腾讯屏蔽了发不出去（……）

另外那个 404 的报错似乎一直存在，无论是 Windows 还是 Docker on linux ，看上去好像没有影响的样子。

感谢协助，应该可以 close 掉了~

**Comment by Tsuk1ko** [comment]
404 好像是方舟公招数据更新的问题，我一会处理一下

**Comment by Tsuk1ko** [comment]
已更
