### ISSUE TITLE
反哔哩哔哩小程序无法识别番剧短链接

### ISSUE THREAD

**Issue by WenyiDong** [Tsuk1ko/CQ-picfinder-robot#59]
1.Bug 描述
希望能正确识别番剧链接
不管是直接B站直接转发还是复制链接都无法识别
2.
![pic1](https://user-images.githubusercontent.com/62381678/80724582-9a35d180-8b34-11ea-95b3-1ad658c5a367.png)
上图是直接转发公主连结第一话，但是识别成了别的
![pic2](https://user-images.githubusercontent.com/62381678/80724840-e123c700-8b34-11ea-92ce-77af955c8661.jpg)
上图是B站一个视频（随手找的），正确解析
![pic3](https://user-images.githubusercontent.com/62381678/80724892-ef71e300-8b34-11ea-9f37-9750f72bc773.jpg)
上图是公主连结第一话的b23短链接和网页链接
3.运行环境
win2016数据中心
node v12.16.1

**Comment by Tsuk1ko** [comment]
不支持番剧链接，也不会支持

后续我会做一下处理来完全忽略番剧链接
