### ISSUE TITLE
ubuntu下怎么使用

### ISSUE THREAD

**Issue by dollarser** [Tsuk1ko/CQ-picfinder-robot#6]
酷q不能直接在Linux下运行，是运行在docker，这个也能在docker里运行么。

**Comment by Tsuk1ko** [comment]
这个 Nodejs 应用可以直接在宿主机上运行，配置酷Q的 cq-http 插件连接宿主机对应ws端口即可

但我个人并不看好酷Q的 docker 版，wine 会有很多兼容性问题，我以前用过并不能跑 cq-http 插件，建议还是用 Windows 主机

**Comment by dollarser** [comment]
了解，非常感谢！
