### ISSUE TITLE
bilibili鄙视插件

### ISSUE THREAD

**Issue by Sakurasun1023** [Tsuk1ko/CQ-picfinder-robot#62]
1. Bug 描述
   分享小程序到群聊中，机器人无反应
2. 截图、日志、配置（issue 内上传图片可直接粘贴）
   这是部分配置文件截图，如不完整后续补充
![image](https://user-images.githubusercontent.com/65067948/81469873-18236800-921a-11ea-8cab-26e600098dbb.png)

3. 运行环境
   - 系统，win server 2016
![image](https://user-images.githubusercontent.com/65067948/81469891-42752580-921a-11ea-86aa-af301f9eb5e6.png)

   - Node 版本 10.16.3
![image](https://user-images.githubusercontent.com/65067948/81469899-4bfe8d80-921a-11ea-8896-2effa5a16c1e.png)
 
以及顺便问下setu功能开了反和谐有没有可能导致账号被tx封禁

非常感谢

**Comment by Tsuk1ko** [comment]
请提供一下酷Q收到的小程序分享消息日志

获取方法为：右击酷Q托盘图标，日志，然后在群内分享小程序，日志会出现一条`[CQ:rich`开头的，右击一下就会复制

为保护隐私，建议将日志中出现的群号和Q号删除

**Comment by Sakurasun1023** [comment]
![VB)~3~B%~H5O7FWDGZW2V(1](https://user-images.githubusercontent.com/65067948/81471654-275be300-9225-11ea-8a4f-c879f75f6616.png)

**Comment by Sakurasun1023** [comment]
[CQ:rich,title=&#91;QQ小程序&#93;哔哩哔哩,content={"detail_1":{"appid":"1109937557"&#44;"desc":"英语课表演赌怪“17张牌你能秒我”"&#44;"host":{"nick":"我想睡觉"&#44;"uin":1169492528}&#44;"icon":"http://miniapp.gtimg.cn/public/appicon/432b76be3a548fc128acaa6c1ec90131_200.jpg"&#44;"preview":"pubminishare-30161.picsz.qpic.cn/3715f108-6e42-4475-b56b-a0979f1e90cd"&#44;"qqdocurl":"https://b23.tv/wFCadY?share_medium=android&amp;share_source=qq&amp;bbid=XYD8298DCB4B69A36800A10FC182B6C54898D&amp;ts=1589020644698"&#44;"scene":1036&#44;"shareTemplateData":{}&#44;"shareTemplateId":"8C8E89B49BE609866298ADDFF2DBABA4"&#44;"title":"哔哩哔哩"&#44;"url":"m.q.qq.com/a/s/fdb37816abbab5dc57fcf73bef532a23"}}]

**Comment by Sakurasun1023** [comment]
群: 476694593 帐号: 1169492528 
[CQ:rich,title=&#91;QQ小程序&#93;哔哩哔哩,content={"detail_1":{"appid":"1109937557"&#44;"desc":"英语课表演赌怪“17张牌你能秒我”"&#44;"host":{"nick":"我想睡觉"&#44;"uin"}&#44;"icon":"http://miniapp.gtimg.cn/public/appicon/432b76be3a548fc128acaa6c1ec90131_200.jpg"&#44;"preview":"pubminishare-30161.picsz.qpic.cn/3715f108-6e42-4475-b56b-a0979f1e90cd"&#44;"qqdocurl":"https://b23.tv/wFCadY?share_medium=android&amp;share_source=qq&amp;bbid=XYD8298DCB4B69A36800A10FC182B6C54898D&amp;ts=1589020644698"&#44;"scene":1036&#44;"shareTemplateData":{}&#44;"shareTemplateId":"8C8E89B49BE609866298ADDFF2DBABA4"&#44;"title":"哔哩哔哩"&#44;"url":"m.q.qq.com/a/s/fdb37816abbab5dc57fcf73bef532a23"}}]

**Comment by Tsuk1ko** [comment]
这看起来应该没问题

1. 程序有没有错误日志
2. 是否是酷Q日志中有机器人发送日志，但群聊中没有任何反应的现象

啊前面忘了回答最后那个问题，不管开不开防和谐，都有被冻结或封禁风险，只要不是被人举报，最多只会冻结

**Comment by Sakurasun1023** [comment]
接bilibili鄙视插件
1.酷q日志中没有向群聊发送信息的日志行为
以及有几个新的疑问希望解答
1.有没有可能能让setu功能在讨论组中使用（现在qq中已经不能创建，查看不到群号之类的）。尝试在白名单群组名单中添加了在酷Q后台看到的讨论组ID，无回应。
2.白名单群组功能好像不起作用。
3.公招功能不知道是不是我配置有误，像机器人发送公招+图片后机器人提示该功能未开启（已在配置文件中true。

如有打扰多多见谅

**Comment by Tsuk1ko** [comment]
那么到底机器人程序有没有错误日志`npm run pm2log`，没有错误输出那我真的不知道什么问题了

------------

1. 程序没做讨论组支持，也不会做
2. 我怀疑你改完配置没重启程序`npm run pm2restart`

**Comment by Sakurasun1023** [comment]
emmmmm   npm run pm2restart后反鄙视跟白名单全部运作了，抱歉看漏这段
![Screenshot_20200510_155034](https://user-images.githubusercontent.com/65067948/81493812-23d46480-92d6-11ea-8f6a-407fd67ab536.jpg)


公招功能程序也有回应了...不过是报错
![Screenshot_20200510_155236](https://user-images.githubusercontent.com/65067948/81493838-731a9500-92d6-11ea-8e08-9866b0bab641.jpg)
![Screenshot_20200510_155329_com microsoft rdc android](https://user-images.githubusercontent.com/65067948/81493851-8f1e3680-92d6-11ea-81b7-7e768265ff40.jpg)
用的是百度的baidubce，已经申请好api跟key。

**Comment by Tsuk1ko** [comment]
这个确实是我这边的问题，稍等我修复下

**Comment by Tsuk1ko** [comment]
OK 了，拉一下最新代码

另外更新公招的命令是`--update-akhr`，没数据的时候会自动拉一次到本地保存，以后只有加了新的公招干员才需要更新数据

**Comment by Sakurasun1023** [comment]
![Screenshot_20200511_083718_com tencent mobileqq](https://user-images.githubusercontent.com/65067948/81514626-b884a400-9362-11ea-8303-d1cdb6734467.jpg)
![Screenshot_20200511_083900](https://user-images.githubusercontent.com/65067948/81514656-e4a02500-9362-11ea-98c5-b15941f21c74.jpg)

可能是我的使用方法有问题，仍旧报错
以及ASCII2d莫名其妙开始报错了....
![Screenshot_20200511_083147](https://user-images.githubusercontent.com/65067948/81514681-0bf6f200-9363-11ea-8e92-8b8865bf2db4.jpg)
![Screenshot_20200511_082943](https://user-images.githubusercontent.com/65067948/81514685-10bba600-9363-11ea-9231-30e2a5fbc907.jpg)

**Comment by Tsuk1ko** [comment]
所有命令除了公招之外都是 linux 式的的啊亲，`--shutdown`，别忽略那俩横杠，程序根本没有重启，启动时会给你发“已连接”的提示的

那句英文提示我不知道哪冒出来的，可能是你是用的别的插件响应的

ascii2d 的这个错误是 aacii2d 返回给你的，和程序无关

**Comment by Sakurasun1023** [comment]
好吧，公招程序依旧报错有没有可能是baidubcr的问题，已经全部重启过了。

**Comment by Tsuk1ko** [comment]
`--update-akhr`，现在更新数据成功与否会有文字反馈

**Comment by Sakurasun1023** [comment]
依旧没有回应，日志应该是这一段
![Screenshot_20200511_090905_com microsoft rdc android](https://user-images.githubusercontent.com/65067948/81515552-2df27380-9367-11ea-8810-e8dfe6d1611c.jpg)

**Comment by Tsuk1ko** [comment]
🤔那晚上再看

**Comment by Sakurasun1023** [comment]
好的，非常感谢。

**Comment by Tsuk1ko** [comment]
没问题啊，你是不是没更新代码……

```
git pull
npm run pm2restart
```

**Comment by Sakurasun1023** [comment]
emmm这两天没看机器人，已经可以了
setu功能有办法加个trigger嘛

好像问的太多了（

**Comment by Tsuk1ko** [comment]
trigger?

**Comment by Sakurasun1023** [comment]
触发器，刚刚试了下正常了，实际上就是指令前缀😂#我要色图这样

可以实现要多个标签的色图嘛，
例如 我要可可萝或者神楽七奈的色图

**Comment by Tsuk1ko** [comment]
https://github.com/Tsuk1ko/CQ-picfinder-robot/wiki/%E9%99%84%E5%8A%A0%E5%8A%9F%E8%83%BD#r18-%E5%92%8C%E5%85%B3%E9%94%AE%E8%AF%8D%E5%8F%82%E6%95%B0
