### ISSUE TITLE
setu服务器爆炸了..

### ISSUE THREAD

**Issue by Hydrochlor** [Tsuk1ko/CQ-picfinder-robot#63]
1.Bug描述
发setu的功能会只会回复瑟图服务器爆炸了...其他功能都正常。
2.截图、日志、配置
发送setu时pm2内的日志是这样的：
![image](https://user-images.githubusercontent.com/65152823/81554871-214b3b00-93ba-11ea-8deb-251ff32cb906.png)
这是聊天截图：
![image](https://user-images.githubusercontent.com/65152823/81554912-345e0b00-93ba-11ea-9c34-04a42d57b1d7.png)
好像是我连接不上服务器的问题..但我试过了挂梯子和不挂梯子都进不去...

3.运行环境
系统是win10,Node版本是10.16.3

小白以前没接触过这些，只能来问大佬了，谢谢大佬！

**Comment by Tsuk1ko** [comment]
挂梯子后需要设置`picfinder.proxy`

**Comment by Hydrochlor** [comment]
那请问不挂梯子的情况呢？不挂梯子就不能使用setu功能吗？

**Comment by Tsuk1ko** [comment]
你是国内机子么，可能网络环境有点差

我的 API 直接套的 Cloudflare，国内正常情况下是能直接访问的

**Comment by Hydrochlor** [comment]
是国内机子，网络环境应该没有问题。但是如果直接访问就是ETIMEDOUT...不过现在我挂梯子然后改proxy就可以了，谢谢大佬
