### ISSUE TITLE
setu服务无法正常使用

### ISSUE THREAD

**Issue by MoeYuki** [Tsuk1ko/CQ-picfinder-robot#64]
1. Bug 描述
  发色图指令回复都是瑟图服务器爆炸了，大概三天前使用时依然是正常的。
 其他服务使用一切正常！
2. 截图、日志、配置
  
![image](https://user-images.githubusercontent.com/61346728/82485277-288aeb00-9b16-11ea-98af-f4d1b7fe5c65.png)
![image](https://user-images.githubusercontent.com/61346728/82485302-32145300-9b16-11ea-89b4-ced3b31e5199.png)

返回403：由于不规范的操作而被拒绝调用。
但只是正常的使用机器人，一个小时前尝试重置了系统把插件全部重新安装，但问题依旧...

3. 运行环境
   - 系统：windows2012 R2
   - Node ：10.16.0

**Comment by Tsuk1ko** [comment]
这个 403 是 HTTP 返回码，不是文档中所说的 code 字段，可能是请求被 WAF 拦截了

在错误日志中找一下出错请求的 url，你尝试在服务器上访问看看会不会也有问题，有问题的话把 url 发过来我看下，注意去掉 apikey 信息

**Comment by MoeYuki** [comment]
非常感谢，不知为什么突然又好了....
emmmm...
在不断的找错误日志在哪，突然间试了下又好了！？
只能认为是服务器抽风了。
谢谢大佬！！
