### ISSUE TITLE
色图 API 能否 加入 根据 某 用户/画师 id 爬图 的 功能

### ISSUE THREAD

**Issue by ygsk10** [Tsuk1ko/CQ-picfinder-robot#65]
1. 根据 某 用户/画师 id 爬图 的 功能
2. 我 超喜欢 @xxxx 收藏  的 色图 啊

Edit1: typo
Edit2: 目前 的 keyword 并 不好用

**Comment by Tsuk1ko** [comment]
抱歉，不打算加

目前 keyword 完全是模糊搜索，好不好用完全看插画标题和标签，我不可能为了这个专门去写一个搜索引擎
