### ISSUE TITLE
请问setu功能中能否加入群内单独屏蔽某人请求的功能？

### ISSUE THREAD

**Issue by Hydrochlor** [Tsuk1ko/CQ-picfinder-robot#66]
1.加入功能：
setu功能中能否加入群内单独屏蔽某人请求的功能？

2.理由：
在某群里面经常被恶意刷屏导致程序特别卡顿甚至直接去世（
请问能否加入该单独屏蔽一个人而该群中其他人仍然可以使用的功能？
谢谢大佬！

**Comment by Tsuk1ko** [comment]
https://github.com/Tsuk1ko/CQ-picfinder-robot/wiki/%E5%A6%82%E4%BD%95%E9%A3%9F%E7%94%A8#%E7%AE%A1%E7%90%86%E8%80%85%E5%91%BD%E4%BB%A4

**Comment by Hydrochlor** [comment]
谢谢大佬！
