### ISSUE TITLE
搜图迷之卡死

### ISSUE THREAD

**Issue by Quan666** [Tsuk1ko/CQ-picfinder-robot#67]
1. Bug 描述
   复现：使用任意图片选择 ‘--book’参数时会报错，最近大概率会发生机器人挂掉（pm2显示在线，有可能卡死），不知道是否和这些报错有关。使用的pm2运行，但出错后并没了重启。此时再给机器人发送图片没有反应。需要重启
从日志文件 2020-6-6 10:28:52 PM 这这之后直到 2020-6-7 12:27:43 AM 我重启插件后 这段时间内别人发图片均无反应。
2. 截图、日志、配置（issue 内上传图片可直接粘贴）
部分截图
![image](https://user-images.githubusercontent.com/32663291/83949320-a9a3eb00-a855-11ea-83ec-7f8bdad22980.png)
![image](https://user-images.githubusercontent.com/32663291/83949453-757cfa00-a856-11ea-8357-0f93b0c049ae.png)
![image](https://user-images.githubusercontent.com/32663291/83949532-f76d2300-a856-11ea-8040-961234cb5a39.png)
日志文件 http://image.myelf.club/error-0.log
3. 运行环境
windows
   - Node 版本
v10.16.3

**Comment by Nek0DAZE** [comment]
SauceNAO的问题，我也遇到了，网页端也有

**Comment by Tsuk1ko** [comment]
建议在国外机器部署，否则挂代理

**Comment by Quan666** [comment]
> 建议在国外机器部署，否则挂代理

代理现在挂上了，但是奇怪的是不知道为什么发生卡死

**Comment by Tsuk1ko** [comment]
所以挂代理之后就正常了是么

**Comment by Quan666** [comment]
> 所以挂代理之后就正常了是么

正常了

**Comment by Tsuk1ko** [comment]
都是捕获了的，只要 error 输出前面带一行时间的都是 catch 了的，所以我也觉得很奇怪不应该卡死

**Comment by Quan666** [comment]
> 都是捕获了的，只要 error 输出前面带一行时间的都是 catch 了的，所以我也觉得很奇怪不应该卡死

那可能是其他未知原因导致的，那就难找了
