### ISSUE TITLE
请问是否有支持代理的功能？

### ISSUE THREAD

**Issue by sdyxxjj123** [Tsuk1ko/CQ-picfinder-robot#68]
我于阿里云服务器上部署了这个机器人，但是ASCII2d搜索 IP被Ban了，但我有一个稳定的VPN连接，是否可以设置机器人走VPN连接？

**Comment by Tsuk1ko** [comment]
[配置项](https://github.com/Tsuk1ko/CQ-picfinder-robot/wiki/%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E8%AF%B4%E6%98%8E)里就有一个 proxy
