### ISSUE TITLE
无法发送图片

### ISSUE THREAD

**Issue by izuiho** [Tsuk1ko/CQ-picfinder-robot#7]
你好，酷Q运行在docker下无法发送图片，日志报错：

文件名不合法,无法发送!(http://127.0.0.1:60233/?key=b8mi56z7ej&url=https://i.pximg.net/img-original/img/2018/02/17/22/03/35/67326337_p0.png)

[CQ:image,file=http://127.0.0.1:60233/?key=b8mi56z7ej&amp;url=https://i.pximg.net/img-original/img/2018/02/17/22/03/35/67326337_p0.png]

**Comment by Tsuk1ko** [comment]
@izuiho 按 README.md 里的 pximgProxy 说明配置一下

**Comment by izuiho** [comment]
@Tsuk1ko 还是这样，而且是境外服务器
logs:
文件名不合法,无法发送!(https://api.pixiv.moe/v2/image/i.pximg.net/img-original/img/2017/05/05/19/31/04/62753253_p0.jpg)
[CQ:image,file=https://api.pixiv.moe/v2/image/i.pximg.net/img-original/img/2017/05/05/19/31/04/62753253_p0.jpg]

**Comment by Tsuk1ko** [comment]
@izuiho 尝试一下 pixiv.cat 的，如果还是不行那目前也暂时没有解决方法

最初你提出来的那个情况是因为你将 nodejs 开在宿主机上，因为我写死了图片地址用 localhost 因此 setu 本地反代功能无法直接使用，如果实在需求的话我下个版本加个自定义本地反代地址的配置吧

**Comment by izuiho** [comment]
@Tsuk1ko 感谢回复，经过你的提示，我通过修改
> https://github.com/Tsuk1ko/CQ-picfinder-robot/blob/master/modules/plugin/pximg.js#L45

达到了目的，不需要麻烦再加个配置了

**Comment by Tsuk1ko** [comment]
@izuiho 是的，这样可以临时解决

**Comment by izuiho** [comment]
@Tsuk1ko 嗯嗯，而且使用 pixiv.cat 也能用
