### ISSUE TITLE
启动报错：cannot find module 'esm'

### ISSUE THREAD

**Issue by misaka10078** [Tsuk1ko/CQ-picfinder-robot#72]
版本2.12.6启动失败
![image](https://user-images.githubusercontent.com/40907636/85241753-7a08fb80-b46f-11ea-9587-2703e0b7d0fe.png)
![image](https://user-images.githubusercontent.com/40907636/85241768-868d5400-b46f-11ea-9ab2-35e71c6edf6b.png)

**Comment by Tsuk1ko** [comment]
没`npm i`或者过程中出现错误，仔细按 wiki 步骤来
