### ISSUE TITLE
开了反和谐后图片反而发不出来

### ISSUE THREAD

**Issue by 10935336** [Tsuk1ko/CQ-picfinder-robot#73]
### 1. Bug 描述
开启反和谐后反而发不出来图片，之前一直正常，最近几天一直无法发图。
查看酷Q缓存，该图片只有200K，并未超过发送上限。
尝试多张图片得到的结果是一样的。
尝试关闭反和谐后能够正常发图。

### 2. 截图、日志、配置（issue 内上传图片可直接粘贴）
            "antiShielding": true,
            "size1200": false,

![image](https://user-images.githubusercontent.com/32383605/85284807-61760100-b4c2-11ea-8916-502138902ef5.png)

### 3. 运行环境
系统：Windows Server 2019 Datacenter    1809   17763.1282
Node 版本：v14.4.0  
NPM版本：6.14.5
CQ-picfinder-robot版本：v2.12.6

**Comment by Tsuk1ko** [comment]
有没有看过缓存里的那张图是否正常，以及程序日志有没有错误

**Comment by 10935336** [comment]
测试几张图都是正常的，也没有特别涩。
pm2log只输出了连接成功。

**Comment by Tsuk1ko** [comment]
那我怀疑这可能是酷Q或者账号的问题，和我这边无关，我也无能为力

**Comment by 10935336** [comment]
其他图片和不开反和谐能正常发送，这就很迷了。
