### ISSUE TITLE
定时提醒功能配置好之后没有提醒

### ISSUE THREAD

**Issue by CiaranZhou** [Tsuk1ko/CQ-picfinder-robot#75]
1. Bug 描述
   - 按照wiki中的步骤配置好定时提醒之后，机器人在设置的时间没有在**群里**提醒。
   - **私聊**将时间设置为`*/5;*;*;*;*`也依然没有任何提醒
   - 在设置过程中机器人没有任何**报错回复**（因为查看了一下源码，发现设置了一些报错机制）
2. 配置
- `--rmd-list`输出如下
![image](https://user-images.githubusercontent.com/33545847/85643150-e41ade00-b6c5-11ea-9fa4-8c8a7d79fec0.png)
- `config.json`中相关配置如下
![image](https://user-images.githubusercontent.com/33545847/85643318-57245480-b6c6-11ea-96ea-b9e9b05fcc94.png)
管理者(`picfinder.admin`)确认设置为本人QQ

3. 运行环境
   - 系统：Ubuntu16.04
   - Node 版本： v10.21.0

顺便一提，有没有交流群(｀_ゝ´)

**Comment by Tsuk1ko** [comment]
修复了，更新即可
