### ISSUE TITLE
启动成功但是机器人并没有向管理者发送已上线，搜图等功能也无法使用

### ISSUE THREAD

**Issue by Annabel0530** [Tsuk1ko/CQ-picfinder-robot#77]
![22](https://user-images.githubusercontent.com/40524485/85947495-153f1c80-b919-11ea-9580-e11e0169accf.png)

**Comment by Tsuk1ko** [comment]
请到酷Q的`data/image/`目录看一下 cqimg 扩展名的文件是不是里面的 url 字段都为空

**Comment by Tsuk1ko** [comment]
先 `npm run stop`

`npm run test` 前台启动后有正常打印出已连接之类的信息么

**Comment by Annabel0530** [comment]
![`V _H F$GYNZ$A`(H_`~%CK](https://user-images.githubusercontent.com/40524485/85950735-a075dd80-b92c-11ea-9121-cd3520303b15.png)
![M(AP4KCXU54$S{Y}KP@V J7](https://user-images.githubusercontent.com/40524485/85950772-d1561280-b92c-11ea-9ce8-8b98ead1a6ab.png)

**Comment by Tsuk1ko** [comment]
依赖没装上，把 node_modules 文件夹删了按照 wiki 流程重新安装检查一下

是不是回退到编译时编译失败了

**Comment by Annabel0530** [comment]
![OUOL2D3K2P$PW7(CE XC2](https://user-images.githubusercontent.com/40524485/85952338-880ac080-b936-11ea-869b-25a00f03ba25.png)
![26OKK7@D$C)JEW%I`U7RM%O](https://user-images.githubusercontent.com/40524485/85952339-89d48400-b936-11ea-9096-2f9667d0c381.png)
全部打过重做还是没反应，跟以前电脑一样的步骤去部署。。。太小白了不知道问题出在哪

**Comment by Tsuk1ko** [comment]
安装命令都没跑完 ctrl+c 干啥……

**Comment by Annabel0530** [comment]
草www 我看下面那行以为成功了 但是还是老样子呀
![{VMYPD V8FUCRM)Y%4EK{IP](https://user-images.githubusercontent.com/40524485/85953286-521d0a80-b93d-11ea-90d5-c6fe16bac401.png)

**Comment by Tsuk1ko** [comment]
这不是还没跑完么，等就完了

**Comment by Annabel0530** [comment]
![77}AL`TP% $8 M82X`F} AX](https://user-images.githubusercontent.com/40524485/85975160-52e98700-b9a5-11ea-9399-1ad04caaeccc.png)
[2020-06-29T05_08_29_659Z-debug.log](https://github.com/Tsuk1ko/CQ-picfinder-robot/files/4843874/2020-06-29T05_08_29_659Z-debug.log)
太难了。。。

**Comment by Tsuk1ko** [comment]
把 node_modules 文件夹删了再试试完整跑一次不要中断它

不行的话换 LTS 版本的 node 重复上述步骤

再不行就告辞吧

**Comment by Annabel0530** [comment]
前后完完整整跑了七次  终于成功连接了  感谢
![Z67G$~EW5KMFE8(~~GTKF2N](https://user-images.githubusercontent.com/40524485/86010573-2b9ac480-ba4e-11ea-977b-08ab6cd71fad.gif)
