### ISSUE TITLE
安装CQ-picfinder-robot这里开始出错，最后运行结果是这样

### ISSUE THREAD

**Issue by guadang** [Tsuk1ko/CQ-picfinder-robot#78]
![QQ截图20200629134913](https://user-images.githubusercontent.com/67555191/85977796-dc35a380-ba0f-11ea-89c9-93ad432cd1d8.png)

**Comment by Tsuk1ko** [comment]
抱歉，不建议纯新手进行部署，请咨询您的朋友来解决这类问题
