### ISSUE TITLE
定时提醒代码问题

### ISSUE THREAD

**Issue by CiaranZhou** [Tsuk1ko/CQ-picfinder-robot#79]
1. Bug 描述
   - 在设置`--time`的参数为`*/5;*;*;*;*`时，经观察实际消息提醒为10分钟一次
   - 按照`cron`的规则应该是5分钟一次
2. 本地复现之后已发现的代码中的bug
`modules/plugin/reminder.js`中的`start`函数（即49~59行）存在以下问题：

   以`--time`的参数为`*/5;*;*;*;*`举例，如果`now`为**9**，52行`while`循环执行完之后`interval.next().getTime()`的值为**10**，则57行计时器中`interval.next().getTime()`的值会是**15**，导致计时器实际是在**6**之后才执行；

   然后递归调用`start`函数，此时`now`的值实际为**15.xxxxx**，重复上述操作之后57行计时器中`interval.next().getTime()`的值会是**25**；

   由此带来的现象就是本例时间分度实际为**10**而不是预期值**5**，也就是说会**导致所有**`cron`**任务隔次执行**
3. 解决方法
   由于我对于JS接触不多，不过在本地复现之后得到一个比较简单的解决方法，供作者参考：

   在**57行while循环**之后，执行一次`interval.prev()`，使迭代器中的值向前一位

**Comment by Tsuk1ko** [comment]
确实，我不小心复制粘贴了调用了两次 `next()`，其实后面 `setTimeout` 的时候直接用前面的 `next` 变量就行，
