### ISSUE TITLE
在插件运行一段时间后会导致酷q无响应，只能强制关闭进程并重启

### ISSUE THREAD

**Issue by MoAccelerator** [Tsuk1ko/CQ-picfinder-robot#80]
系统windows10 1909
node.js 12.18.2
在插件运行一段时间后（大约一个小时内），酷q就会卡死，尝试关闭本插件后运行酷q，发现一切正常 并没有出现卡死的情况，最近也没有对其他插件进行更新 也没有对酷q版本进行升级之类的操作，之前本来用的是2.13.2版本的插件，在出现这个问题之后我尝试升级到2.13.3后 发现情况并没有得到改善
![image](https://user-images.githubusercontent.com/45995147/87490855-4fc6ea00-c679-11ea-886e-7981c78cd07e.png)
![image](https://user-images.githubusercontent.com/45995147/87490676-db8c4680-c678-11ea-8cb1-f06dc4ae673b.png)
![image](https://user-images.githubusercontent.com/45995147/87490708-ef37ad00-c678-11ea-9ff2-67f09a467bdf.png)

**Comment by Tsuk1ko** [comment]
尝试使用更低版本的 cq-http 插件看看，我在用 4.12.x 没有问题

cq-http 那边也有人提了跟你这个状况类似的 issue，有可能是 cq-http 的问题

https://github.com/richardchien/coolq-http-api/issues/352

**Comment by MoAccelerator** [comment]
> 尝试使用更低版本的 cq-http 插件看看，我在用 4.12.x 没有问题
> 
> cq-http 那边也有人提了跟你这个状况类似的 issue，有可能是 cq-http 的问题
> 
> [richardchien/coolq-http-api#352](https://github.com/richardchien/coolq-http-api/issues/352)

好的 谢谢！ 我这就去试试！
