### ISSUE TITLE
能否增加对搜图尺寸/长宽比进行判定并相应提示的功能

### ISSUE THREAD

**Issue by assassingyk** [Tsuk1ko/CQ-picfinder-robot#83]
如题，不知能否增加一项对搜图时图片尺寸/长宽比进行判定并在符合条件时进行相应提示的功能。

具体来说是隔壁群经常看到有人在搜漫画时用手机滚动截屏截下的连续好几页漫画截屏去搜，自然是搜不出结果，每次看到了我都专门去提醒下截成单页搜图……
不知道能不能加一项，当被搜索图片长宽比大于一定数值（例如1.5~2倍手机屏比例）时，自动发消息提示“疑似长截屏，建议截取出单页搜索”之类。一般的图很少有这种比例的应该也不会对正常搜图有太大影响。

（只是突然脑洞想出来的功能，如果实现起来很麻烦还请直接无视我就好……）

**Comment by Tsuk1ko** [comment]
单独检测长宽感觉必要性不大，不如直接在相似度过低提示里补充提示

反正这类搜不出的话相似度肯定低，而就算在搜图前判断了长宽比也总不能不让搜（

**Comment by assassingyk** [comment]
好像也是，那我看看在相似度过低提示里加一句好了）
