### ISSUE TITLE
something wrong

### ISSUE THREAD

**Issue by acgtap** [Tsuk1ko/CQ-picfinder-robot#9]
![image](https://user-images.githubusercontent.com/40010177/59142535-57d24600-89f2-11e9-8c82-c413ef26e41b.png)

**Comment by Tsuk1ko** [comment]
请按[部署步骤](https://github.com/Tsuk1ko/CQ-picfinder-robot#3-%E5%BC%80%E6%90%9E)复制一份`config.default.json`重命名为`config.json`

**Comment by acgtap** [comment]
![image](https://user-images.githubusercontent.com/40010177/59143065-0c239a80-89fa-11e9-9902-d66f9de23850.png)

**Comment by Tsuk1ko** [comment]
https://github.com/Tsuk1ko/CQ-picfinder-robot#2-coolq-http-api-%E6%8F%92%E4%BB%B6

**Comment by acgtap** [comment]
行了喵
